<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en-gb">
<link rel="self" type="application/atom+xml" href="http://www.classicshell.net/forum/feed.php?f=8&amp;t=3332" />

<title>Classic Shell</title>
<subtitle>Classic Shell support forum</subtitle>
<link href="http://www.classicshell.net/forum/index.php" />
<updated>2014-11-28T13:15:53-07:00</updated>

<author><name><![CDATA[Classic Shell]]></name></author>
<id>http://www.classicshell.net/forum/feed.php?f=8&amp;t=3332</id>
<entry>
<author><name><![CDATA[Techn]]></name></author>
<updated>2014-11-28T13:15:53-07:00</updated>
<published>2014-11-28T13:15:53-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15853#p15853</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15853#p15853"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15853#p15853"><![CDATA[
How do I go about doing that?<br /><br />I had a quick search and downloaded shell extensions manager and shell menu view. But they both bring up a long list of entries.<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=4867">Techn</a> — Fri Nov 28, 2014 1:15 pm</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Ivo]]></name></author>
<updated>2014-11-28T10:41:55-07:00</updated>
<published>2014-11-28T10:41:55-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15852#p15852</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15852#p15852"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15852#p15852"><![CDATA[
This usually indicates a problem with a shell extension. Disable them one by one and see which one it is. A slowdown like that usually means it is trying to access the network and timing out when it is initialized (once for each new window).<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=2">Ivo</a> — Fri Nov 28, 2014 10:41 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Techn]]></name></author>
<updated>2014-11-28T08:55:46-07:00</updated>
<published>2014-11-28T08:55:46-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15851#p15851</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15851#p15851"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15851#p15851"><![CDATA[
I am having a similar problem but didn't want to create a new thread.<br /><br />When I right click on any file in windows explorer that explorer window hangs for exactly 7 seconds. However this only happens every time a new explorer window is opened. It does not happen on the second right click after the first has eventually completed.<br /><br />Is there anyway to fix this? It is hugely frustrating.<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=4867">Techn</a> — Fri Nov 28, 2014 8:55 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Ivo]]></name></author>
<updated>2014-11-08T07:57:51-07:00</updated>
<published>2014-11-08T07:57:51-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15558#p15558</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15558#p15558"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15558#p15558"><![CDATA[
The &quot;module not found&quot; error is generated by NavShExt.dll, which is part of Norton. Nothing to do with Classic Shell.<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=2">Ivo</a> — Sat Nov 08, 2014 7:57 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Labrat0116]]></name></author>
<updated>2014-11-08T07:50:08-07:00</updated>
<published>2014-11-08T07:50:08-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15556#p15556</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15556#p15556"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15556#p15556"><![CDATA[
<div class="quotetitle">Labrat0116 wrote:</div><div class="quotecontent"><br /><div class="quotetitle">Ivo wrote:</div><div class="quotecontent">Modules are DLL files.<br /><br />You may try running Process Monitor and see what DLLs the Explorer process is trying to load.<br /><br />The other menu is IObit's Start Menu 8.<br /></div>I Uninstalled OIbit Start Menu 8, right clicked on a random Windows Explorer folder, got another hang issue and generated a new .dmp file.<br /><br />I'll uploaded after I get off work tonight.</div>Ok, I uninstalled SM 8, I also disable the Windows Credentials Password log-in.<br /><br /><br /> The Right-Click DOES work now, a bit slow, but it's working.<br /><br /> Still generating CrashDump files. Here's the latest below.<br /><br /><!-- m --><a class="postlink" href="https://drive.google.com/file/d/0BxIk-qhp2ganS2Vld3RhT0l2UkE/view?usp=sharing">https://drive.google.com/file/d/0BxIk-q ... sp=sharing</a><!-- m --><p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=4726">Labrat0116</a> — Sat Nov 08, 2014 7:50 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Labrat0116]]></name></author>
<updated>2014-11-07T12:19:18-07:00</updated>
<published>2014-11-07T12:19:18-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15549#p15549</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15549#p15549"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15549#p15549"><![CDATA[
<div class="quotetitle">Ivo wrote:</div><div class="quotecontent"><br />Modules are DLL files.<br /><br />You may try running Process Monitor and see what DLLs the Explorer process is trying to load.<br /><br />The other menu is IObit's Start Menu 8.<br /></div>I Uninstalled OIbit Start Menu 8, right clicked on a random Windows Explorer folder, got another hang issue and generated a new .dmp file.<br /><br /> I'll uploaded after I get off work tonight.<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=4726">Labrat0116</a> — Fri Nov 07, 2014 12:19 pm</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Ivo]]></name></author>
<updated>2014-11-07T08:15:37-07:00</updated>
<published>2014-11-07T08:15:37-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15548#p15548</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15548#p15548"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15548#p15548"><![CDATA[
Modules are DLL files.<br /><br />You may try running Process Monitor and see what DLLs the Explorer process is trying to load.<br /><br />The other menu is IObit's Start Menu 8.<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=2">Ivo</a> — Fri Nov 07, 2014 8:15 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Labrat0116]]></name></author>
<updated>2014-11-07T07:25:37-07:00</updated>
<published>2014-11-07T07:25:37-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15545#p15545</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15545#p15545"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15545#p15545"><![CDATA[
<div class="quotetitle">Ivo wrote:</div><div class="quotecontent"><br />The error you have is &quot;module not found&quot;. However the dump is incomplete and it is not clear what module that is.<br />On the other hand I see you have another start menu software running at the same time. I recommend you uninstall it.<br /></div>What are modules ??<br /><br />How do I find out what it is ?<br /><br />What's the name of the other start menu ?<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=4726">Labrat0116</a> — Fri Nov 07, 2014 7:25 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Ivo]]></name></author>
<updated>2014-11-07T00:41:57-07:00</updated>
<published>2014-11-07T00:41:57-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15542#p15542</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15542#p15542"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15542#p15542"><![CDATA[
The error you have is &quot;module not found&quot;. However the dump is incomplete and it is not clear what module that is.<br />On the other hand I see you have another start menu software running at the same time. I recommend you uninstall it.<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=2">Ivo</a> — Fri Nov 07, 2014 12:41 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Labrat0116]]></name></author>
<updated>2014-11-06T23:47:47-07:00</updated>
<published>2014-11-06T23:47:47-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15541#p15541</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15541#p15541"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15541#p15541"><![CDATA[
<div class="quotetitle">Labrat0116 wrote:</div><div class="quotecontent"><br />Can you open this link ??<br /><br /><!-- m --><a class="postlink" href="https://drive.google.com/file/d/0BxIk-qhp2gancDJSdC1ETm52aUU/view?usp=sharing">https://drive.google.com/file/d/0BxIk-q ... sp=sharing</a><!-- m --><br /></div>So how does one open a .dmp file to reveal the contents ?<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=4726">Labrat0116</a> — Thu Nov 06, 2014 11:47 pm</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Labrat0116]]></name></author>
<updated>2014-11-06T11:30:47-07:00</updated>
<published>2014-11-06T11:30:47-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15529#p15529</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15529#p15529"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15529#p15529"><![CDATA[
Can you open this link ??<br /><br /><!-- m --><a class="postlink" href="https://drive.google.com/file/d/0BxIk-qhp2gancDJSdC1ETm52aUU/view?usp=sharing">https://drive.google.com/file/d/0BxIk-q ... sp=sharing</a><!-- m --><p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=4726">Labrat0116</a> — Thu Nov 06, 2014 11:30 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Labrat0116]]></name></author>
<updated>2014-11-06T11:27:48-07:00</updated>
<published>2014-11-06T11:27:48-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15528#p15528</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15528#p15528"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15528#p15528"><![CDATA[
<div class="quotetitle">Ivo wrote:</div><div class="quotecontent"><br />This usually means a problem with some shell extension. Create a crash dump using these instructions: <!-- l --><a class="postlink-local" href="http://www.classicshell.net/forum/viewtopic.php?f=12&amp;t=6">viewtopic.php?f=12&amp;t=6</a><!-- l --><br /></div>Ok, mission accomplished. Just don't know how the share the file here..... yet. <br /><br /> How do I share a file out of my Google Drive ?<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=4726">Labrat0116</a> — Thu Nov 06, 2014 11:27 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Ivo]]></name></author>
<updated>2014-11-06T10:26:23-07:00</updated>
<published>2014-11-06T10:26:23-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15527#p15527</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15527#p15527"/>
<title type="html"><![CDATA[Re: Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15527#p15527"><![CDATA[
This usually means a problem with some shell extension. Create a crash dump using these instructions: <!-- l --><a class="postlink-local" href="http://www.classicshell.net/forum/viewtopic.php?f=12&amp;t=6">viewtopic.php?f=12&amp;t=6</a><!-- l --><p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=2">Ivo</a> — Thu Nov 06, 2014 10:26 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Labrat0116]]></name></author>
<updated>2014-11-06T10:22:32-07:00</updated>
<published>2014-11-06T10:22:32-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15526#p15526</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15526#p15526"/>
<title type="html"><![CDATA[Right Click Hangs Windows Explorer]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=3332&amp;p=15526#p15526"><![CDATA[
Everytime I do a Right Click while using Windows Explorer on my laptop, it HANGS endlessly. I'm forced to do a Shutdown and pull out the battery to reset my laptop.<br /><br /> I don't know if this has something to do with Classic Shell or not, but my leaning in this direction.<br /><br /> I'm at loss at this point ?<br /><br /> Ideas ?<br /><br /> TIA<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=4726">Labrat0116</a> — Thu Nov 06, 2014 10:22 am</p><hr />
]]></content>
</entry>
</feed>