<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en-gb">
<link rel="self" type="application/atom+xml" href="http://www.classicshell.net/forum/feed.php?f=7&amp;t=8161" />

<title>Classic Shell</title>
<subtitle>Classic Shell support forum</subtitle>
<link href="http://www.classicshell.net/forum/index.php" />
<updated>2017-12-10T02:47:05-07:00</updated>

<author><name><![CDATA[Classic Shell]]></name></author>
<id>http://www.classicshell.net/forum/feed.php?f=7&amp;t=8161</id>
<entry>
<author><name><![CDATA[Jcee]]></name></author>
<updated>2017-12-10T02:47:05-07:00</updated>
<published>2017-12-10T02:47:05-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=35000#p35000</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=35000#p35000"/>
<title type="html"><![CDATA[Re: Transfer Classic Desktop to Win10 desktop]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=35000#p35000"><![CDATA[
you are confusing the desktop with the start menu.<br />but there is no simple way to transfer all of your shortcuts from classic shell to windows 10's start menu without pinning them 1 at a time.<br />Those shortcuts (and the rest of your settings) should be preserved if you later reinstall classic shell<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=62">Jcee</a> — Sun Dec 10, 2017 2:47 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Zoettl]]></name></author>
<updated>2017-12-10T02:26:58-07:00</updated>
<published>2017-12-10T02:26:58-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=34999#p34999</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=34999#p34999"/>
<title type="html"><![CDATA[Re: Transfer Classic Desktop to Win10 desktop]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=34999#p34999"><![CDATA[
Thank you<br /><br />Because I have two desktops , one were I can install the Win10 Tiles and one like Win7 .<br />I thought the Win7 desktop is generated by the ClassicShell Programm<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=28010">Zoettl</a> — Sun Dec 10, 2017 2:26 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Ivo]]></name></author>
<updated>2017-12-09T09:13:36-07:00</updated>
<published>2017-12-09T09:13:36-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=34991#p34991</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=34991#p34991"/>
<title type="html"><![CDATA[Re: Transfer Classic Desktop to Win10 desktop]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=34991#p34991"><![CDATA[
There is no such thing as Classic Desktop. The desktop is part of Windows. It will stay the same even after you remove Classic Shell. Only the start menu will change.<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=2">Ivo</a> — Sat Dec 09, 2017 9:13 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Zoettl]]></name></author>
<updated>2017-12-09T08:39:38-07:00</updated>
<published>2017-12-09T08:39:38-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=34990#p34990</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=34990#p34990"/>
<title type="html"><![CDATA[Transfer Classic Desktop to Win10 desktop]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=8161&amp;p=34990#p34990"><![CDATA[
Is it possible to transfer my  Classic Desktop to Win10 desktop bevore I deinstall ClassicShell ?<br /><br />Is there a simple way to install links to programms and files on the Win10 desktop similar to the Classic desktop ?<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=28010">Zoettl</a> — Sat Dec 09, 2017 8:39 am</p><hr />
]]></content>
</entry>
</feed>