<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en-gb">
<link rel="self" type="application/atom+xml" href="http://www.classicshell.net/forum/feed.php?f=12&amp;t=8010" />

<title>Classic Shell</title>
<subtitle>Classic Shell support forum</subtitle>
<link href="http://www.classicshell.net/forum/index.php" />
<updated>2017-11-24T12:51:29-07:00</updated>

<author><name><![CDATA[Classic Shell]]></name></author>
<id>http://www.classicshell.net/forum/feed.php?f=12&amp;t=8010</id>
<entry>
<author><name><![CDATA[Ivo]]></name></author>
<updated>2017-11-24T12:51:29-07:00</updated>
<published>2017-11-24T12:51:29-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34830#p34830</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34830#p34830"/>
<title type="html"><![CDATA[Re: Win 10 desktop continually restarts, until CS 4.3.1 remo]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34830#p34830"><![CDATA[
This looks like a crash in Explorer. You need to capture a crash dump. Look at the link at the top of this page for instructions.<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=2">Ivo</a> — Fri Nov 24, 2017 12:51 pm</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Kimbo No1]]></name></author>
<updated>2017-10-31T00:31:56-07:00</updated>
<published>2017-10-31T00:31:56-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34622#p34622</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34622#p34622"/>
<title type="html"><![CDATA[Re: Win 10 desktop continually restarts, until CS 4.3.1 remo]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34622#p34622"><![CDATA[
I refer to the initial and a follow up posting generated by John Gray and to the response offered by Gaurav.<br /><br />I am not knowledgeable about the internal operation of Windows 10 but I respectfully ask the developers of Classic Shell to reconsider their future participation in offering and extending the life of ClassicShell so as the provide an alternative to Windows 10 so called start menu and tile menu system.<br /><br />I have just installed windows 10 1709 (after waiting 4 months for the upgraded contents to be serviceable) and after arranging the customization of the existing ClassicShell (4.3.1 installed within version 1703, I am now experiencing the same issues exactly as John Gray has reported.<br /><br />I believe that there is something in excess if <strong>13 million users around the world </strong>who have downloaded and probably installed ClassicShell over recent times and also probably effectively from the introduction of windows 10,<br /><br />So far there are two users (John and myself) who have reported the same issues with the Desktop refreshing every 4 or 5 seconds with little ability to stop the refreshing - there must be heaps more users who have the same issues experienced within this forum discussion.<br /><br />Is there any chance to learn that 'refreshing' repair could be made and that future servicing will be attended to look after Windows 10 inadequacies be made to ClassicShell so as to meet the shortfalls of Windows 10 start system by repairing version 4.3.1 and later versions of ClassicShell so that faults associated by Windows 10 will be built into ClassicShell.<br /><br />I plead - Help those of us who live by ClassicShell.... please?<br /><br />Regards to you all<br /><br />Kim<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=19429">Kimbo No1</a> — Tue Oct 31, 2017 12:31 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[John Gray]]></name></author>
<updated>2017-10-14T08:33:11-07:00</updated>
<published>2017-10-14T08:33:11-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34438#p34438</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34438#p34438"/>
<title type="html"><![CDATA[Re: Win 10 desktop continually restarts, until CS 4.3.1 remo]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34438#p34438"><![CDATA[
Thank you very much for your response!<br /><br />Perhaps I could paraphrase it as &quot;Classic Shell will become less and less likely to work as Microsoft continues to produce updates for Windows 10 - unless the user reinstalls Windows 10 from the latest ISO each time there is a major update, every six months&quot;...<br /><br />I had, in fact, used the Classic Shell [removal] Utility before reinstalling it the final time, but that didn't help matters. I have used it again to remove CS from the laptop.<br /><br />I shall hold off on a complete reinstallation of Windows 10 from ISO until after the Fall Creators Update due on or after 17th October.<br />I wonder whether the promised Start Menu 'improvements' will make it any easier to use?<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=25336">John Gray</a> — Sat Oct 14, 2017 8:33 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[Gaurav]]></name></author>
<updated>2017-10-14T05:10:36-07:00</updated>
<published>2017-10-14T05:10:36-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34436#p34436</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34436#p34436"/>
<title type="html"><![CDATA[Re: Win 10 desktop continually restarts, until CS 4.3.1 remo]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34436#p34436"><![CDATA[
The way Windows 10 is serviced and updated, it routinely creates crashing issues for Explorer because Microsoft's upgrade process is imperfect even after years of trying and cannot even properly migrate desktop app settings after the upgrade - it ends up deleting certain configuration in the Registry. On a clean install of Windows 10's latest release, Classic Shell works. But often when in-place upgrades are done, Windows Setup damages it or causes serious issues due to their imperfect update process causing a partially installed state where Classic Shell crashes Explorer. I recommend you to stay with Windows 7 or 8.1 if you want to use Classic Shell.<br /><br />You could capture a crash dump as per these instructions: <!-- l --><a class="postlink-local" href="http://www.classicshell.net/forum/viewtopic.php?f=12&amp;t=6">viewtopic.php?f=12&amp;t=6</a><!-- l --> but there are so many instability issues in general with Windows 10 that it is always going to give you problems. It's not a good, well-engineered system.<br /><br />Another thing you can try is download the Classic Shell Utility from here: <!-- m --><a class="postlink" href="http://www.mediafire.com/download/3ukeryzw41qpfz8/ClassicShellUtility.exe">http://www.mediafire.com/download/3uker ... tility.exe</a><!-- m --> and use it to clean all traces of Classic Shell from your existing installation, including all settings. Then try a clean install of the newest version.<br /><br />However we cannot guarantee it won't crash or break again because Microsoft designed Windows 10 to routinely break desktop apps that integrate deeply with the system.<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=54">Gaurav</a> — Sat Oct 14, 2017 5:10 am</p><hr />
]]></content>
</entry>
<entry>
<author><name><![CDATA[John Gray]]></name></author>
<updated>2017-10-14T03:48:55-07:00</updated>
<published>2017-10-14T03:48:55-07:00</published>
<id>http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34435#p34435</id>
<link href="http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34435#p34435"/>
<title type="html"><![CDATA[Win 10 desktop continually restarts, until CS 4.3.1 removed]]></title>

<content type="html" xml:base="http://www.classicshell.net/forum/viewtopic.php?t=8010&amp;p=34435#p34435"><![CDATA[
Laptop is an HP EliteBook 8460p, which apparently does not support Windows 10, although it has been running Windows 10 quite happily for at least a year.<br /><br />I was asked to apply all the outstanding Windows Updates (about a year's worth!) to the Windows 10 Pro 64-bit operating system, so installed Classic Shell 4.3.1 (all options) and began.  <br /><br />After the latest and biggest update to version 1703, when the desktop came up it began continually wiping itself and redrawing all the desktop icons and the &quot;bottom line&quot; icons, in a continuous loop about 3-5 seconds in length.  It was almost impossible to do anything, apart from Ctrl-Alt-Del and Task Manager, where I was able with some difficulty to run TASKKILL CLASSICSTARTMENU.EXE, or to End Process on the same task in the list.  That 'solved' the problem of the continual desktop restart.<br /><br />I can't find any reference to this problem in the forum, so wonder what I can do to generate any diagnostic information.<br /><br />[As an aside, I had the same problem on a second 'identical' Elitebook 8460p, and reinstalled Windows 10 from a version 1703 ISO, then put on Classic Shell 4.3.1, and it works perfectly!]<p>Statistics: Posted by <a href="http://www.classicshell.net/forum/memberlist.php?mode=viewprofile&amp;u=25336">John Gray</a> — Sat Oct 14, 2017 3:48 am</p><hr />
]]></content>
</entry>
</feed>