//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ClassicExplorer.rc
//
#define IDI_APPICON                     1
#define IDI_UP                          2
#define IDI_UPDISABLED                  3
#define IDI_UP2NORMAL                   4
#define IDI_UP2PRESSED                  5
#define IDI_UP2HOT                      6
#define IDI_UP2DISABLED                 7
#define IDR_CLASSICEXPLORER             101
#define IDR_EXPLORERBAND                102
#define IDR_EXPLORERBHO                 104
#define IDR_SHAREOVERLAY                105
#define IDD_FILEMULTI                   129
#define IDD_FILE                        130
#define IDC_LINKMORE                    204
#define IDC_CHECKBHO                    205
#define IDC_CHECKCOPY                   206
#define IDC_STATICPROMPT1               207
#define IDC_CHECKBIG                    207
#define IDC_STATICPROMPT2               208
#define IDD_FILEMULTIR                  208
#define IDD_FILER                       209
#define IDC_STATICICON                  209
#define IDC_CHECK1                      210
#define IDD_FOLDERMULTI                 210
#define IDC_CHECK2                      211
#define IDD_FOLDER                      211
#define IDC_CHECK3                      212
#define IDD_FOLDERR                     212
#define IDC_CHECK4                      213
#define IDD_FOLDERMULTIR                213
#define IDC_CHECK5                      214
#define IDC_CHECK6                      215
#define IDR_CLASSICCOPYEXT              216
#define IDC_CHECKNOFADE                 218
#define IDC_CHECKSIZE                   219
#define IDC_CHECKAUTO                   220
#define IDC_CHECKCOPYFOLDER             221
#define IDC_CHECK7                      222
#define IDC_CHECK8                      223
#define IDC_COMBOSTYLE                  224
#define IDC_CHECKOFFSET                 225
#define IDC_CHECKUP                     226
#define IDC_CHECKTITLE                  227
#define IDC_CHECKICON                   228
#define IDC_CHECKCRUMBS                 229
#define IDC_CHECKSHARED                 230
#define IDC_CHECKSHAREDEXP              231
#define IDC_CHECKCOPYEXP                233
#define IDC_CHECKMORE                   234
#define IDC_CHECKINFO                   235
#define IDC_COMBOCOMMAND                239
#define IDC_EDITLABEL                   240
#define IDC_EDITTIP                     241
#define IDC_BUTTONLINK                  242
#define IDC_BUTTONCOMMAND               243
#define IDC_EDITICON                    245
#define IDC_BUTTONICON                  246
#define IDC_EDITICOND                   247
#define IDC_BUTTONICOND                 248
#define IDC_STATICCOMMAND               251
#define IDC_STATICLINK                  252
#define IDC_STATICTEXT                  253
#define IDC_STATICINFOTIP               254
#define IDC_STATICICOND                 255
#define IDC_ICONN                       256
#define IDC_ICOND                       257
#define IDC_COMBOLINK                   258
#define IDC_STATICICON1                 260
#define IDC_BUTTONRESET                 261
#define IDC_STATICFNAME                 1003
#define IDC_STATICSRCSIZE               1004
#define IDC_STATICSRCTIME               1005
#define IDC_STATICDSTSIZE               1006
#define IDC_STATICDSTTIME               1007
#define IDC_STATICSRCICON               1008
#define IDC_STATICDSTICON               1009
#define IDD_CUSTOMTOOLBAR               2001
#define IDS_APP_TITLE                   2001
#define IDS_SETTINGS_BTN                2002
#define IDS_NEW_SETTINGS1               2003
#define IDS_NEW_SETTINGS2               2004
#define IDS_SETTINGS_TITLE              2005
#define IDS_SETTINGS_TITLE_VER          2006
#define IDS_LANGUAGE_SETTINGS           2010
#define IDS_TOOLBAR_SETTINGS            2011
#define IDS_BIG_BUTTONS                 2012
#define IDS_BIG_BUTTONS_TIP             2013
#define IDS_SMALL_SIZE                  2014
#define IDS_SMALL_SIZE_TIP              2015
#define IDS_LARGE_SIZE                  2016
#define IDS_LARGE_SIZE_TIP              2017
#define IDS_MENU_SIZE                   2018
#define IDS_MENU_SIZE_TIP               2019
#define IDS_SAME_SIZE                   2020
#define IDS_SAME_SIZE_TIP               2021
#define IDS_LIST_MODE                   2022
#define IDS_LIST_MODE_TIP               2023
#define IDS_RESIZEABLE                  2024
#define IDS_RESIZEABLE_TIP              2025
#define IDS_BUTTONS_SETTINGS            2026
#define IDS_NAVIGATION_SETTINGS         2027
#define IDS_TREE_STYLE                  2028
#define IDS_TREE_STYLE_TIP              2029
#define IDS_XPCLASSIC                   2030
#define IDS_XPCLASSIC_TIP               2031
#define IDS_XPSIMPLE                    2032
#define IDS_XPSIMPLE_TIP                2033
#define IDS_VISTA                       2034
#define IDS_VISTA_TIP                   2035
#define IDS_TREE_SPACING                2036
#define IDS_TREE_SPACING_TIP            2037
#define IDS_NO_FADE                     2038
#define IDS_NO_FADE_TIP                 2039
#define IDS_FULL_INDENT                 2040
#define IDS_FULL_INDENT_TIP             2041
#define IDS_NAVIGATE                    2042
#define IDS_NAVIGATE_TIP                2043
#define IDS_NAV_DELAY                   2044
#define IDS_NAV_DELAY_TIP               2045
#define IDS_ALT_ENTER                   2046
#define IDS_ALT_ENTER_TIP               2047
#define IDS_FIX_SCROLL                  2048
#define IDS_FIX_SCROLL_TIP              2049
#define IDS_TITLE_SETTINGS              2050
#define IDS_SHOW_CAPTION                2051
#define IDS_SHOW_CAPTION_TIP            2052
#define IDS_SHOW_ICON                   2053
#define IDS_SHOW_ICON_TIP               2054
#define IDS_NO_BREADCRUMBS              2055
#define IDS_NO_BREADCRUMBS_TIP          2056
#define IDS_ADDRESS_HISTORY             2057
#define IDS_ADDRESS_HISTORY_TIP         2058
#define IDS_NORMAL_HISTORY              2059
#define IDS_NORMAL_HISTORY_TIP          2060
#define IDS_SIMPLE_PATH                 2061
#define IDS_SIMPLE_PATH_TIP             2062
#define IDS_EXTENDED_PATH               2063
#define IDS_EXTENDED_PATH_TIP           2064
#define IDS_HIDE_SEARCH                 2065
#define IDS_HIDE_SEARCH_TIP             2066
#define IDS_UP_SETTINGS                 2067
#define IDS_SHOW_UP                     2068
#define IDS_SHOW_UP_TIP                 2069
#define IDS_DONT_SHOW                   2070
#define IDS_DONT_SHOW_TIP               2071
#define IDS_BEFORE_BACK                 2072
#define IDS_BEFORE_BACK_TIP             2073
#define IDS_AFTER_BACK                  2074
#define IDS_AFTER_BACK_TIP              2075
#define IDS_UP_NORMAL                   2076
#define IDS_UP_NORMAL_TIP               2077
#define IDS_UP_HOT                      2078
#define IDS_UP_HOT_TIP                  2079
#define IDS_UP_PRESSED                  2080
#define IDS_UP_PRESSED_TIP              2081
#define IDS_UP_DISABLED                 2082
#define IDS_UP_DISABLED_TIP             2083
#define IDS_UP_SIZE                     2084
#define IDS_UP_SIZE_TIP                 2085
#define IDS_STATUS_SETTINGS             2086
#define IDS_FREE_SPACE                  2087
#define IDS_FREE_SPACE_TIP              2088
#define IDS_INFO_TIP                    2089
#define IDS_INFO_TIP_TIP                2090
#define IDS_FORCE_REFRESH               2091
#define IDS_FORCE_REFRESH_TIP           2092
#define IDS_FILE_SETTINGS               2093
#define IDS_FILE_UI                     2094
#define IDS_FILE_UI_TIP                 2095
#define IDS_FOLDER_UI                   2096
#define IDS_FOLDER_UI_TIP               2097
#define IDS_ALERT_LEVEL                 2098
#define IDS_ALERT_LEVEL_TIP             2099
#define IDS_NO_ALERT                    2100
#define IDS_NO_ALERT_TIP                2101
#define IDS_SYS_FILES                   2102
#define IDS_SYS_FILES_TIP               2103
#define IDS_RO_FILES                    2104
#define IDS_RO_FILES_TIP                2105
#define IDS_MORE                        2106
#define IDS_MORE_TIP                    2107
#define IDS_MORE_DELAY                  2108
#define IDS_MORE_DELAY_TIP              2109
#define IDS_FILE_EXPLORER               2110
#define IDS_FILE_EXPLORER_TIP           2111
#define IDS_FILEPANE_SETTINGS           2112
#define IDS_SHARE                       2113
#define IDS_SHARE_TIP                   2114
#define IDS_SHARE_ICON                  2115
#define IDS_SHARE_ICON_TIP              2116
#define IDS_SHARE_EXPLORER              2117
#define IDS_SHARE_EXPLORER_TIP          2118
#define IDS_HEADERS                     2119
#define IDS_HEADERS_TIP                 2120
#define IDS_SCROLLBAR                   2121
#define IDS_SCROLLBAR_TIP               2122
#define IDS_SCROLLBAR_DEFAULT           2123
#define IDS_SCROLLBAR_DEFAULT_TIP       2124
#define IDS_SCROLLBAR_ON                2125
#define IDS_SCROLLBAR_ON_TIP            2126
#define IDS_SCROLLBAR_OFF               2127
#define IDS_SCROLLBAR_OFF_TIP           2128
#define IDS_COMMAND_TIP                 2129
#define IDS_LINK_TIP                    2130
#define IDS_TEXT_TIP                    2131
#define IDS_TIP_TIP                     2132
#define IDS_ICON_TIP                    2133
#define IDS_ICOND_TIP                   2134
#define IDS_RESTORE_TIP                 2135
#define IDS_SEPARATOR_TIP               2136
#define IDS_UP_TIP                      2137
#define IDS_CUT_TIP                     2138
#define IDS_COPY_TIP                    2139
#define IDS_PASTE_TIP                   2140
#define IDS_DELETE_TIP                  2141
#define IDS_PROPERTIES_TIP              2142
#define IDS_EMAIL_TIP                   2143
#define IDS_SETTINGS_TIP                2144
#define IDS_REFRESH_TIP                 2145
#define IDS_STOP_TIP                    2146
#define IDS_RENAME_TIP                  2147
#define IDS_MOVETO_TIP                  2148
#define IDS_COPYTO_TIP                  2149
#define IDS_UNDO_TIP                    2150
#define IDS_REDO_TIP                    2151
#define IDS_SELECTALL_TIP               2152
#define IDS_DESELECT_TIP                2153
#define IDS_INVERT_TIP                  2154
#define IDS_BACK_TIP                    2155
#define IDS_FORWARD_TIP                 2156
#define IDS_VIEWTILES_TIP               2157
#define IDS_VIEWDEATAILS_TIP            2158
#define IDS_VIEWLIST_TIP                2159
#define IDS_VIEWCONTENT_TIP             2160
#define IDS_VIEWICONS1_TIP              2161
#define IDS_VIEWICONS2_TIP              2162
#define IDS_VIEWICONS3_TIP              2163
#define IDS_VIEWICONS4_TIP              2164
#define IDS_OPEN_TIP                    2165
#define IDS_CUSTOM_TIP                  2166
#define IDS_NEWFOLDER_TIP               2167
#define IDS_SCROLLTIP                   2168
#define IDS_SCROLLTIP_TIP               2169
#define IDS_NAV_DEFAULT                 2170
#define IDS_NAV_DEFAULT_TIP             2171
#define IDS_NAV_KBD                     2172
#define IDS_NAV_KBD_TIP                 2173
#define IDS_NAV_ALWAYS                  2174
#define IDS_NAV_ALWAYS_TIP              2175
#define IDS_ALT_D                       2176
#define IDS_ALT_D_TIP                   2177
#define IDS_SORT_TIP                    2178
#define IDS_GROUP_TIP                   2179
#define IDS_PASTE_SHORTCUT_TIP          2180
#define IDS_UP_HOTKEY                   2181
#define IDS_UP_HOTKEY_TIP               2182
#define IDS_MAP_DRIVE_TIP               2183
#define IDS_DISCONNECT_DRIVE_TIP        2184
#define IDS_CUSTOMIZEFOLDER_TIP         2185
#define IDS_SEPARATOR_ITEM              2186
#define IDS_UP_ITEM                     2187
#define IDS_CUT_ITEM                    2188
#define IDS_COPY_ITEM                   2189
#define IDS_PASTE_ITEM                  2190
#define IDS_PASTE_LNK_ITEM              2191
#define IDS_DELETE_ITEM                 2192
#define IDS_PROPERTIES_ITEM             2193
#define IDS_EMAIL_ITEM                  2194
#define IDS_SETTINGS_ITEM               2195
#define IDS_REFRESH_ITEM                2196
#define IDS_STOP_ITEM                   2197
#define IDS_RENAME_ITEM                 2198
#define IDS_NEWFOLDER_ITEM              2199
#define IDS_MOVETO_ITEM                 2200
#define IDS_COPYTO_ITEM                 2201
#define IDS_UNDO_ITEM                   2202
#define IDS_REDO_ITEM                   2203
#define IDS_SELECTALL_ITEM              2204
#define IDS_DESELECT_ITEM               2205
#define IDS_INVERT_ITEM                 2206
#define IDS_BACK_ITEM                   2207
#define IDS_FORWARD_ITEM                2208
#define IDS_MAP_DRIVE_ITEM              2209
#define IDS_DISCONNECT_ITEM             2210
#define IDS_CUSTOMIZE_ITEM              2211
#define IDS_VIEWTILES_ITEM              2212
#define IDS_VIEWDETAILS_ITEM            2213
#define IDS_VIEWLIST_ITEM               2214
#define IDS_VIEWCONTENT_ITEM            2215
#define IDS_VIEWICONS1_ITEM             2216
#define IDS_VIEWICONS2_ITEM             2217
#define IDS_VIEWICONS3_ITEM             2218
#define IDS_VIEWICONS4_ITEM             2219
#define IDS_OPEN_ITEM                   2220
#define IDS_SORYBY_ITEM                 2221
#define IDS_GROUPBY_ITEM                2222
#define IDS_CUSTOM_ITEM                 2223
#define IDS_SHOWSTATUSBAR               2224
#define IDS_SHOWSTATUSBAR_TIP           2225
#define IDS_SHOW_ZONE                   2226
#define IDS_SHOW_ZONE_TIP               2227
#define IDS_SHARE_HIDDEN                2228
#define IDS_SHARE_HIDDEN_TIP            2229
#define IDS_NAVPANE_ITEM                2230
#define IDS_NAVPANE_TIP                 2231
#define IDS_DETAILSPANE_ITEM            2232
#define IDS_DETAILSPANE_TIP             2233
#define IDS_PREVIEWPANE_ITEM            2234
#define IDS_PREVIEWPANE_TIP             2235
#define IDS_SHOW_EXTENSIONS             2236
#define IDS_SHOW_EXTENSIONS_TIP         2237
#define IDS_HIDDEN_FILES                2238
#define IDS_HIDDEN_FILES_TIP            2239
#define IDS_SYSTEM_FILES                2240
#define IDS_SYSTEM_FILES_TIP            2241
#define IDS_ZIP_ITEM                    2242
#define IDS_ZIP_TIP                     2243
#define IDS_STATUS_FONT                 2244
#define IDS_STATUS_FONT_TIP             2245
#define IDS_FOLDEROPTIONS               2246
#define IDS_FOLDEROPTIONS_TIP           2247

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        227
#define _APS_NEXT_COMMAND_VALUE         32769
#define _APS_NEXT_CONTROL_VALUE         262
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
