<?xml version="1.0"?>
<Settings component="StartMenu" version="4.3.1">
	<MenuStyle value="Classic1"/>
	<ShiftClick value="WindowsMenu"/>
	<WinKey value="Nothing"/>
	<ShiftWin value="Nothing"/>
	<ShiftRight value="0"/>
	<Computer value="Hide"/>
	<Favorites value="Hide"/>
	<ControlPanel value="Menu"/>
	<Network value="Menu"/>
	<Printers value="Menu"/>
	<ConfirmLogOff value="1"/>
	<Search value="0"/>
	<Help value="0"/>
	<RecentPrograms value="None"/>
	<RecentMetroApps value="0"/>
	<RecentProgsTop value="0"/>
	<EnableJumplists value="1"/>
	<StartScreenShortcut value="0"/>
	<CheckWinUpdates value="0"/>
	<ScrollType value="Scroll"/>
	<EnableAccessibility value="0"/>
	<PreCacheIcons value="1"/>
	<DelayIcons value="1"/>
	<SearchBox value="Normal"/>
	<SearchInternet value="0"/>
	<LargeIconSize value="32"/>
	<InvertMetroIcons value="0"/>
	<MaxMainMenuWidth value="60"/>
	<SubMenuAnimationAlways value="1"/>
	<MenuCaption value="Windows 8.1 Professional"/>
	<AeroGlass value="0"/>
	<SkinC1 value="Classic skin3"/>
	<SkinVariationC1 value=""/>
	<SkinOptionsC1>
		<Line>CAPTION=1</Line>
		<Line>USER_IMAGE=0</Line>
		<Line>USER_NAME=0</Line>
		<Line>CENTER_NAME=0</Line>
		<Line>SMALL_ICONS=0</Line>
		<Line>THICK_BORDER=1</Line>
		<Line>SOLID_SELECTION=1</Line>
	</SkinOptionsC1>
	<SkinC2 value="Classic skin2"/>
	<SkinVariationC2 value=""/>
	<SkinOptionsC2>
		<Line>E55CEDD3|C26EAF5D|86F3669D|5225DC46|5D3248DD|E87963C3|80316ABF|</Line>
	</SkinOptionsC2>
	<SkinW7 value="Windows 8"/>
	<SkinVariationW7 value=""/>
	<SkinOptionsW7>
		<Line>C26EAF5D|5D3248DC|1FC64124|5EA361A2|6EDFA36A|2E838408|22C9A1E2|0663DC39|</Line>
	</SkinOptionsW7>
	<EnableStartButton value="1"/>
	<StartButtonType value="ClasicButton"/>
	<StartButtonIcon value="%SystemDrive%\Transfer\favicon.ico"/>
	<StartButtonIconSize value="0"/>
	<StartButtonText value="$Menu.Start"/>
	<CustomTaskbar value="1"/>
	<TaskbarLook value="Opaque"/>
	<TaskbarOpacity value="90"/>
	<TaskbarColor value="0"/>
	<TaskbarTextColor value="0"/>
	<SkipMetro value="1"/>
	<DisableHotCorner value="DisableAll"/>
	<MenuItems1>
		<Line>Items=COLUMN_PADDING,ProgramsMenu,COLUMN_BREAK,FavoritesItem,RecentDocumentsItem,ComputerItem,SettingsMenu,SearchMenu,HelpItem,RunItem,SEPARATOR,LogOffItem,UndockItem,DisconnectItem,ShutdownBoxItem,SearchBoxItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Tip=$Menu.ProgramsTip</Line>
		<Line>ProgramsMenu.Icon=imageres.dll, 5322</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=$Menu.Favorites</Line>
		<Line>FavoritesItem.Icon=imageres.dll,1024</Line>
		<Line>RecentDocumentsItem.Items=UserFilesItem,UserDocumentsItem,UserPicturesItem</Line>
		<Line>RecentDocumentsItem.Command=recent_documents</Line>
		<Line>RecentDocumentsItem.Label=$Menu.Documents</Line>
		<Line>RecentDocumentsItem.Icon=%SystemRoot%\System32\mydocs.dll, 100</Line>
		<Line>RecentDocumentsItem.Settings=ITEMS_FIRST</Line>
		<Line>UserFilesItem.Command=user_files</Line>
		<Line>UserFilesItem.Tip=$Menu.UserFilesTip</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>SettingsMenu.Items=ControlPanelItem,SEPARATOR,SecurityItem,NetworkItem,PrintersItem,TaskbarSettingsItem,ProgramsFeaturesItem,SEPARATOR,MenuSettingsItem</Line>
		<Line>SettingsMenu.Command=settings</Line>
		<Line>SettingsMenu.Label=$Menu.Settings</Line>
		<Line>SettingsMenu.Icon=mycomput.dll, 201</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Tip=$Menu.ControlPanelTip</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>ControlPanelItem.Settings=TRACK_RECENT</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Tip=$Menu.SecurityTip</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>TaskbarSettingsItem.Command=taskbar_settings</Line>
		<Line>TaskbarSettingsItem.Label=$Menu.Taskbar</Line>
		<Line>TaskbarSettingsItem.Tip=$Menu.TaskbarTip</Line>
		<Line>TaskbarSettingsItem.Icon=shell32.dll,40</Line>
		<Line>ProgramsFeaturesItem.Command=programs_features</Line>
		<Line>ProgramsFeaturesItem.Label=$Menu.Features</Line>
		<Line>ProgramsFeaturesItem.Tip=$Menu.FeaturesTip</Line>
		<Line>ProgramsFeaturesItem.Icon=shell32.dll,271</Line>
		<Line>MenuSettingsItem.Command=menu_settings</Line>
		<Line>MenuSettingsItem.Label=$Menu.ClassicSettings</Line>
		<Line>MenuSettingsItem.Tip=$Menu.SettingsTip</Line>
		<Line>MenuSettingsItem.Icon=,1</Line>
		<Line>SearchMenu.Items=SearchFilesItem,SearchPrinterItem,SearchComputersItem,SearchPeopleItem</Line>
		<Line>SearchMenu.Command=search</Line>
		<Line>SearchMenu.Label=$Menu.Search</Line>
		<Line>SearchMenu.Icon=shell32.dll,323</Line>
		<Line>SearchFilesItem.Command=search_files</Line>
		<Line>SearchFilesItem.Label=$Menu.SearchFiles</Line>
		<Line>SearchFilesItem.Tip=$Menu.SearchFilesTip</Line>
		<Line>SearchFilesItem.Icon=shell32.dll,134</Line>
		<Line>SearchPrinterItem.Command=search_printer</Line>
		<Line>SearchPrinterItem.Label=$Menu.SearchPrinter</Line>
		<Line>SearchPrinterItem.Tip=$Menu.SearchPrintersTip</Line>
		<Line>SearchPrinterItem.Icon=shell32.dll,1006</Line>
		<Line>SearchComputersItem.Command=search_computers</Line>
		<Line>SearchComputersItem.Label=$Menu.SearchComputers</Line>
		<Line>SearchComputersItem.Tip=$Menu.SearchComputersTip</Line>
		<Line>SearchComputersItem.Icon=shell32.dll,135</Line>
		<Line>SearchPeopleItem.Command=search_people</Line>
		<Line>SearchPeopleItem.Label=$Menu.SearchPeople</Line>
		<Line>SearchPeopleItem.Icon=shell32.dll,269</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Tip=$Menu.HelpTip</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Tip=$Menu.RunTip</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>LogOffItem.Link=%SystemDrive%\Classic\logoff.vbs</Line>
		<Line>LogOffItem.Label=Завер&amp;шение сеанса</Line>
		<Line>LogOffItem.Tip=$Menu.LogOffTip</Line>
		<Line>LogOffItem.Icon=shell32.dll,325</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Tip=$Menu.UndockTip</Line>
		<Line>UndockItem.Icon=shell32.dll,331</Line>
		<Line>DisconnectItem.Command=disconnect</Line>
		<Line>DisconnectItem.Label=$Menu.Disconnect</Line>
		<Line>DisconnectItem.Tip=$Menu.DisconnectTip</Line>
		<Line>DisconnectItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Items=SwitchUserItem,LockItem,SleepItem,HibernateItem,RestartItem,ShutdownItem</Line>
		<Line>ShutdownBoxItem.Link=%SystemDrive%\Classic\shutdown.vbs</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Settings=SPLIT</Line>
		<Line>SwitchUserItem.Command=switch_user</Line>
		<Line>SwitchUserItem.Label=$Menu.SwitchUser</Line>
		<Line>SwitchUserItem.Tip=$Menu.SwitchUserTip</Line>
		<Line>SwitchUserItem.Icon=none</Line>
		<Line>LockItem.Command=lock</Line>
		<Line>LockItem.Label=$Menu.Lock</Line>
		<Line>LockItem.Tip=$Menu.LockTip</Line>
		<Line>LockItem.Icon=none</Line>
		<Line>SleepItem.Command=sleep</Line>
		<Line>SleepItem.Label=$Menu.Sleep</Line>
		<Line>SleepItem.Tip=$Menu.SleepTip</Line>
		<Line>SleepItem.Icon=none</Line>
		<Line>HibernateItem.Command=hibernate</Line>
		<Line>HibernateItem.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem.Tip=$Menu.HibernateTip</Line>
		<Line>HibernateItem.Icon=none</Line>
		<Line>RestartItem.Link=%SystemDrive%\Classic\restart.vbs</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Tip=$Menu.RestartTip</Line>
		<Line>RestartItem.Icon=none</Line>
		<Line>ShutdownItem.Link=%SystemDrive%\Classic\shutdown.vbs</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Tip=$Menu.ShutdownTip</Line>
		<Line>ShutdownItem.Icon=none</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP|TRACK_RECENT</Line>
	</MenuItems1>
	<CascadingMenu value="0"/>
	<DisablePinExt value="1"/>
</Settings>
