<?xml version="1.0"?>
<Settings component="StartMenu" version="4.3.0">
	<MenuStyle value="Win7"/>
	<MouseClick value="Both"/>
	<ShiftClick value="WindowsMenu"/>
	<WinKey value="Both"/>
	<ShiftWin value="Nothing"/>
	<MiddleClick value="WindowsMenu"/>
	<ShiftRight value="0"/>
	<Documents value="Hide"/>
	<MaxRecentDocuments value="11"/>
	<UserFiles value="Show"/>
	<UserDocuments value="Hide"/>
	<UserPictures value="Hide"/>
	<ControlPanel value="Hide"/>
	<Network value="Hide"/>
	<Printers value="Hide"/>
	<ShowAppsMenu value="0"/>
	<Help value="0"/>
	<ProgramsStyle value="Inline"/>
	<AllProgramsMetro value="1"/>
	<FoldersFirst value="1"/>
	<OpenPrograms value="0"/>
	<HideProgramsMetro value="0"/>
	<PinnedPrograms value="PinnedItems"/>
	<RecentPrograms value="None"/>
	<RecentMetroApps value="1"/>
	<EnableJumplists value="0"/>
	<ShutdownCommand value="CommandHibernate"/>
	<HybridShutdown value="0"/>
	<ProgramsWidth value="33"/>
	<JumplistWidth value="33"/>
	<MinMainHeight value="19"/>
	<StartScreenShortcut value="0"/>
	<HighlightNew value="0"/>
	<CheckWinUpdates value="0"/>
	<ScrollType value="NoScroll"/>
	<SameSizeColumns value="0"/>
	<ExpandFolderLinks value="0"/>
	<EnableAccessibility value="0"/>
	<SearchBox value="Normal"/>
	<SearchPath value="0"/>
	<SearchKeywords value="0"/>
	<SearchSubWord value="0"/>
	<SearchFiles value="0"/>
	<SearchInternet value="1"/>
	<LargeIconSize value="32"/>
	<InvertMetroIcons value="1"/>
	<MaxMainMenuWidth value="60"/>
	<MaxMenuWidth value="90"/>
	<OverrideDPI value="90"/>
	<MainMenuAnimation value="Fade"/>
	<SubMenuAnimationSpeed value="400"/>
	<SubMenuAnimationAlways value="1"/>
	<MenuCaption value="Windows 10"/>
	<NumericSort value="1"/>
	<FontSmoothing value="ClearType"/>
	<EnableGlass value="1"/>
	<GlassOverride value="0"/>
	<GlassOpacity value="3"/>
	<SkinW7 value="Metro"/>
	<SkinVariationW7 value=""/>
	<SkinOptionsW7>
		<Line>USER_IMAGE=1</Line>
		<Line>SMALL_ICONS=0</Line>
		<Line>LARGE_FONT=1</Line>
		<Line>ICON_FRAMES=0</Line>
		<Line>OPAQUE=0</Line>
	</SkinOptionsW7>
	<EnableStartButton value="0"/>
	<StartButtonType value="AeroButton"/>
	<CustomTaskbar value="0"/>
	<TaskbarLook value="Opaque"/>
	<SkipMetro value="1"/>
	<MenuItems7>
		<Line>Item1.Command=user_files</Line>
		<Line>Item1.Settings=NOEXPAND</Line>
		<Line>Item2.Command=downloads</Line>
		<Line>Item2.Settings=NOEXPAND</Line>
		<Line>Item3.Link=%USERPROFILE%\OneDrive - The Estée Lauder Companies Inc</Line>
		<Line>Item3.Label=OneDrive</Line>
		<Line>Item3.Settings=NOEXPAND</Line>
		<Line>Item4.Command=lib_documents</Line>
		<Line>Item4.Tip=$Menu.DocumentsLibTip</Line>
		<Line>Item4.Settings=NOEXPAND</Line>
		<Line>Item5.Command=lib_pictures</Line>
		<Line>Item5.Tip=$Menu.PicturesLibTip</Line>
		<Line>Item5.Settings=NOEXPAND</Line>
		<Line>Item6.Command=separator</Line>
		<Line>Item7.Command=computer</Line>
		<Line>Item7.Settings=NOEXPAND</Line>
		<Line>Item8.Command=separator</Line>
		<Line>Item9.Command=control_panel</Line>
		<Line>Item9.Label=$Menu.ControlPanel</Line>
		<Line>Item9.Tip=$Menu.ControlPanelTip</Line>
		<Line>Item9.Settings=TRACK_RECENT|NOEXPAND</Line>
		<Line>Item10.Command=separator</Line>
		<Line>Item11.Command=apps</Line>
		<Line>Item11.Label=$Menu.Apps</Line>
		<Line>Item11.Icon=,2</Line>
		<Line>Item11.Settings=TRACK_RECENT</Line>
		<Line>Item12.Command=run</Line>
	</MenuItems7>
	<CascadingMenu value="1"/>
</Settings>
