<?xml version="1.0"?>
<Settings component="StartMenu" version="4.0.2">
	<MenuStyle value="Classic2"/>
	<WinKey value="WindowsMenu"/>
	<ConfirmLogOff value="1"/>
	<Undock value="0"/>
	<HideProgramsMetro value="1"/>
	<RecentPrograms value="Recent"/>
	<RecentMetroApps value="0"/>
	<MaxRecentPrograms value="7"/>
	<RecentProgsTop value="0"/>
	<RemoteShutdown value="1"/>
	<MainSortOnce value="1"/>
	<HighlightNew value="0"/>
	<MenuDelay value="600"/>
	<SplitMenuDelay value="400"/>
	<EnableDragDrop value="0"/>
	<DragHideDelay value="4000"/>
	<EnableAccessibility value="0"/>
	<MainMenuAnimation value="None"/>
	<SubMenuAnimation value="None"/>
	<FontSmoothing value="ClearType"/>
	<NoTaskbarTransparency2 value="1"/>
	<SkinC2 value="Windows Aero"/>
	<SkinVariationC2 value="Blue"/>
	<SkinOptionsC2 value="E55CEDD3|C26EAF5D|86F3669C|5225DC47|5D3248DC|1FC64125|5EA361A2|0663DC38|"/>
	<EnableStartButton value="1"/>
	<StartButtonType value="AeroButton"/>
	<SkipMetro value="1"/>
	<DisableHotCorner value="DisableStart"/>
	<OpenMouseMonitor value="0"/>
	<MenuItems2>
		<Line>Items=COLUMN_PADDING,SEPARATOR,ProgramsMenu,AppsMenu,SearchBoxItem,COLUMN_BREAK,FavoritesItem,UserFilesItem,UserDocumentsItem,UserPicturesItem,ComputerItem,DocumentsItem,SEPARATOR,ControlPanelItem,SecurityItem,NetworkItem,PrintersItem,SEPARATOR,SearchMenu,HelpItem,RunItem,COLUMN_PADDING,SEPARATOR,ShutdownBoxItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>AppsMenu.Command=apps</Line>
		<Line>AppsMenu.Label=$Menu.Apps</Line>
		<Line>AppsMenu.Icon=shell32.dll,326</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP|TRACK_RECENT</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=$Menu.Favorites</Line>
		<Line>FavoritesItem.Icon=shell32.dll,322</Line>
		<Line>UserFilesItem.Command=user_files</Line>
		<Line>UserFilesItem.Tip=$Menu.UserFilesTip</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>DocumentsItem.Command=recent_documents</Line>
		<Line>DocumentsItem.Settings=ITEMS_FIRST</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>SearchMenu.Items=SearchFilesItem,SearchPrinterItem,SearchComputersItem,SearchPeopleItem</Line>
		<Line>SearchMenu.Command=search</Line>
		<Line>SearchMenu.Label=$Menu.Search</Line>
		<Line>SearchMenu.Icon=shell32.dll,323</Line>
		<Line>SearchFilesItem.Command=search_files</Line>
		<Line>SearchFilesItem.Label=$Menu.SearchFiles</Line>
		<Line>SearchFilesItem.Icon=shell32.dll,134</Line>
		<Line>SearchPrinterItem.Command=search_printer</Line>
		<Line>SearchPrinterItem.Label=$Menu.SearchPrinter</Line>
		<Line>SearchPrinterItem.Icon=shell32.dll,1006</Line>
		<Line>SearchComputersItem.Command=search_computers</Line>
		<Line>SearchComputersItem.Label=$Menu.SearchComputers</Line>
		<Line>SearchComputersItem.Icon=shell32.dll,135</Line>
		<Line>SearchPeopleItem.Command=search_people</Line>
		<Line>SearchPeopleItem.Label=$Menu.SearchPeople</Line>
		<Line>SearchPeopleItem.Icon=shell32.dll,269</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>ShutdownBoxItem.Items=SwitchUserItem,LogOffItem,LockItem,SEPARATOR,SleepItem,HibernateItem,SEPARATOR,RestartItem,UndockItem,DisconnectItem,ShutdownItem</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Settings=SPLIT</Line>
		<Line>SwitchUserItem.Command=switch_user</Line>
		<Line>SwitchUserItem.Label=$Menu.SwitchUser</Line>
		<Line>SwitchUserItem.Icon=none</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.LogoffShort</Line>
		<Line>LogOffItem.Icon=none</Line>
		<Line>LockItem.Command=lock</Line>
		<Line>LockItem.Label=$Menu.Lock</Line>
		<Line>LockItem.Icon=none</Line>
		<Line>SleepItem.Command=sleep</Line>
		<Line>SleepItem.Label=$Menu.Sleep</Line>
		<Line>SleepItem.Icon=none</Line>
		<Line>HibernateItem.Command=hibernate</Line>
		<Line>HibernateItem.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem.Icon=none</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Icon=none</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Icon=none</Line>
		<Line>DisconnectItem.Command=disconnect</Line>
		<Line>DisconnectItem.Label=$Menu.Disconnect</Line>
		<Line>DisconnectItem.Icon=none</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Icon=none</Line>
	</MenuItems2>
</Settings>
