<?xml version="1.0"?>
<Settings component="StartMenu" version="4.2.5">
	<ShiftClick value="WindowsMenu"/>
	<ShiftWin value="WindowsMenu"/>
	<ShiftRight value="0"/>
	<MaxRecentDocuments value="50"/>
	<SortRecentDocuments value="Date"/>
	<ControlPanelCategories value="1"/>
	<ProgramsStyle value="Inline"/>
	<PinnedPrograms value="PinnedItems"/>
	<MaxRecentPrograms value="45"/>
	<RecentProgsTop value="0"/>
	<RecentProgKeys value="Normal"/>
	<MaxJumplists value="50"/>
	<HybridShutdown value="0"/>
	<ProgramsWidth value="50"/>
	<JumplistWidth value="50"/>
	<MinMainHeight value="35"/>
	<StartScreenShortcut value="0"/>
	<ScrollType value="Auto"/>
	<ExpandFolderLinks value="1"/>
	<InvertMetroIcons value="0"/>
	<MaxMenuWidth value="75"/>
	<SubMenuAnimation value="Fade"/>
	<MenuFadeSpeed value="250"/>
	<NoTaskbarTransparency2 value="0"/>
	<GlassOverride value="0"/>
	<GlassOpacity value="25"/>
	<SkinW7 value="Midnight"/>
	<SkinVariationW7 value=""/>
	<SkinOptionsW7 value="C26EAF5D|5D3248DC|1FC64125|5EA361A2|00000000|6EDFA36A|BD38A82C|678B22C1|8FE87E82|"/>
	<EnableStartButton value="0"/>
	<StartButtonType value="AeroButton"/>
	<SkipMetro value="0"/>
	<CustomTaskbar value="1"/>
	<TaskbarLook value="Glass"/>
	<TaskbarOpacity value="25"/>
	<TaskbarColor value="0"/>
	<OpenMouseMonitor value="0"/>
	<MenuItems7>
		<Line>Item1.Link=%USERPROFILE%\App's</Line>
		<Line>Item1.Label=App's</Line>
		<Line>Item1.Settings=TRACK_RECENT</Line>
		<Line>Item2.Link=%USERPROFILE%\Games</Line>
		<Line>Item2.Label=Games</Line>
		<Line>Item2.Settings=TRACK_RECENT</Line>
		<Line>Item3.Command=separator</Line>
		<Line>Item4.Command=user_files</Line>
		<Line>Item4.Settings=NOEXPAND</Line>
		<Line>Item5.Command=computer</Line>
		<Line>Item5.Settings=NOEXPAND</Line>
		<Line>Item6.Command=user_documents</Line>
		<Line>Item6.Settings=NOEXPAND</Line>
		<Line>Item7.Command=downloads</Line>
		<Line>Item7.Settings=NOEXPAND</Line>
		<Line>Item8.Command=user_pictures</Line>
		<Line>Item8.Settings=NOEXPAND</Line>
		<Line>Item9.Command=user_music</Line>
		<Line>Item9.Settings=NOEXPAND</Line>
		<Line>Item10.Command=user_videos</Line>
		<Line>Item10.Settings=ITEM_DISABLED</Line>
		<Line>Item11.Command=separator</Line>
		<Line>Item12.Command=homegroup</Line>
		<Line>Item13.Command=games</Line>
		<Line>Item13.Settings=TRACK_RECENT|ITEM_DISABLED</Line>
		<Line>Item14.Command=favorites</Line>
		<Line>Item14.Settings=ITEM_DISABLED</Line>
		<Line>Item15.Command=recent_documents</Line>
		<Line>Item16.Command=network</Line>
		<Line>Item17.Command=network_connections</Line>
		<Line>Item17.Settings=ITEM_DISABLED</Line>
		<Line>Item18.Command=separator</Line>
		<Line>Item19.Command=control_panel</Line>
		<Line>Item19.Settings=TRACK_RECENT</Line>
		<Line>Item20.Command=pc_settings</Line>
		<Line>Item20.Settings=TRACK_RECENT</Line>
		<Line>Item21.Command=admin</Line>
		<Line>Item21.Settings=TRACK_RECENT|ITEM_DISABLED</Line>
		<Line>Item22.Command=devices</Line>
		<Line>Item22.Settings=ITEM_DISABLED</Line>
		<Line>Item23.Command=defaults</Line>
		<Line>Item23.Settings=ITEM_DISABLED</Line>
		<Line>Item24.Command=help</Line>
		<Line>Item24.Settings=ITEM_DISABLED</Line>
		<Line>Item25.Command=run</Line>
		<Line>Item26.Command=apps</Line>
		<Line>Item26.Settings=ITEM_DISABLED</Line>
		<Line>Item27.Command=windows_security</Line>
	</MenuItems7>
	<CascadeAll value="0"/>
	<SkinA value="Full Glass"/>
	<SkinVariationA value=""/>
	<SkinOptionsA value="1FC64124|"/>
	<CascadingMenu value="1"/>
</Settings>
