<?xml version="1.0"?>
<Settings component="StartMenu" version="4.2.5">
	<MenuStyle value="Classic2"/>
	<ConfirmLogOff value="1"/>
	<EnableJumplists value="1"/>
	<MenuCaption value=""/>
	<MenuUsername value=""/>
	<SkinC2 value="XP Luna BB REVB "/>
	<SkinVariationC2 value=""/>
	<SkinOptionsC2 value="5D3248DC|1FC64124|E55CEDD2|FAE7E73B|C26EAF5D|86F3669C|5225DC46|"/>
	<SkipMetro value="1"/>
	<MenuItems2>
		<Line>Items=COLUMN_PADDING,ProgramsMenu,AppsMenu,SearchBoxItem,COLUMN_BREAK,UserDocumentsItem,RecentDocumentsItem,UserPicturesItem,CustomItem,FavoritesItem,ComputerItem,SEPARATOR,ControlPanelItem,SecurityItem,NetworkItem,PrintersItem,SEPARATOR,HelpItem,SearchMenu,RunItem,COLUMN_PADDING,SEPARATOR,ShutdownBoxItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>AppsMenu.Command=apps</Line>
		<Line>AppsMenu.Label=$Menu.Apps</Line>
		<Line>AppsMenu.Icon=,2</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP|TRACK_RECENT</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Label=My Documents</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>RecentDocumentsItem.Command=recent_documents</Line>
		<Line>RecentDocumentsItem.Label=My Recent Documents</Line>
		<Line>RecentDocumentsItem.Settings=ITEMS_FIRST</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Label=My Pictures&amp;                    &amp;</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>CustomItem.Link=Music | %USERPROFILE%\Music</Line>
		<Line>CustomItem.Label=My Music</Line>
		<Line>CustomItem.Settings=NOEXPAND</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=$Menu.Favorites</Line>
		<Line>FavoritesItem.Icon=shell32.dll,322</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>ComputerItem.Label=My Computer</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Tip=$Menu.ControlPanelTip</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>ControlPanelItem.Settings=TRACK_RECENT</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Tip=$Menu.SecurityTip</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Tip=$Menu.HelpTip</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>SearchMenu.Items=SearchFilesItem,SearchPrinterItem,SearchComputersItem,SearchPeopleItem</Line>
		<Line>SearchMenu.Command=search</Line>
		<Line>SearchMenu.Label=$Menu.Search</Line>
		<Line>SearchMenu.Icon=shell32.dll,323</Line>
		<Line>SearchFilesItem.Command=search_files</Line>
		<Line>SearchFilesItem.Label=$Menu.SearchFiles</Line>
		<Line>SearchFilesItem.Tip=$Menu.SearchFilesTip</Line>
		<Line>SearchFilesItem.Icon=shell32.dll,134</Line>
		<Line>SearchPrinterItem.Command=search_printer</Line>
		<Line>SearchPrinterItem.Label=$Menu.SearchPrinter</Line>
		<Line>SearchPrinterItem.Tip=$Menu.SearchPrintersTip</Line>
		<Line>SearchPrinterItem.Icon=shell32.dll,1006</Line>
		<Line>SearchComputersItem.Command=search_computers</Line>
		<Line>SearchComputersItem.Label=$Menu.SearchComputers</Line>
		<Line>SearchComputersItem.Tip=$Menu.SearchComputersTip</Line>
		<Line>SearchComputersItem.Icon=shell32.dll,135</Line>
		<Line>SearchPeopleItem.Command=search_people</Line>
		<Line>SearchPeopleItem.Label=$Menu.SearchPeople</Line>
		<Line>SearchPeopleItem.Icon=shell32.dll,269</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Tip=$Menu.RunTip</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>ShutdownBoxItem.Items=LogOffItem,ShutdownBoxItem2,SEPARATOR</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Settings=INLINE|SPLIT</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.LogOffShort</Line>
		<Line>LogOffItem.Tip=$Menu.LogOffTip</Line>
		<Line>LogOffItem.Icon=%SystemRoot%\System32\shell32.dll, 325</Line>
		<Line>LogOffItem.Settings=OPEN_UP_CHILDREN</Line>
		<Line>ShutdownBoxItem2.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem2.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem2.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem2.Settings=SPLIT</Line>
	</MenuItems2>
</Settings>
