<?xml version="1.0"?>
<Settings component="StartMenu" version="3.6.6">
	<DefaultMenuStyle value="Classic"/>
	<ShiftClick value="Nothing"/>
	<ShiftWin value="Nothing"/>
	<Computer value="Hide"/>
	<Documents value="Hide"/>
	<UserFiles value="Menu"/>
	<UserDocuments value="Hide"/>
	<UserPictures value="Hide"/>
	<Printers value="Hide"/>
	<LogOff value="0"/>
	<Undock value="0"/>
	<RecentPrograms value="0"/>
	<MainSortZA value="0"/>
	<ScrollType value="NoScroll"/>
	<FontSmoothing value="Default"/>
	<SearchBox value="Normal"/>
	<Skin1 value="Smoked Glass"/>
	<SkinVariation1 value=""/>
	<SkinOptions1 value="DA60029A|E55CEDD2|BD80CDB3|C26EAF5C|86F3669C|5225DC46|5D3248DC|1FC64124|5EA361A2|"/>
	<ShowNewFolder value="0"/>
	<EnableExit value="0"/>
	<EnableExplorer value="0"/>
	<MenuItems>
		<Line>Items=COLUMN_PADDING,ProgramsMenu,AppsMenu,COLUMN_BREAK,FavoritesItem,ComputerItem,SettingsMenu,SearchMenu,HelpItem,RunItem,SEPARATOR,LogOffItem,UndockItem,DisconnectItem,ShutdownBoxItem,SearchBoxItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>AppsMenu.Command=apps</Line>
		<Line>AppsMenu.Label=$Menu.Apps</Line>
		<Line>AppsMenu.Icon=shell32.dll,326</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=$Menu.Favorites</Line>
		<Line>FavoritesItem.Icon=shell32.dll,322</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>SettingsMenu.Items=ControlPanelItem,SEPARATOR,SecurityItem,NetworkItem,PrintersItem,TaskbarSettingsItem,ProgramsFeaturesItem,SEPARATOR,MenuSettingsItem</Line>
		<Line>SettingsMenu.Command=settings</Line>
		<Line>SettingsMenu.Label=$Menu.Settings</Line>
		<Line>SettingsMenu.Icon=shell32.dll,330</Line>
		<Line>ControlPanelItem.Command=control_panel_categories</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>TaskbarSettingsItem.Command=taskbar_settings</Line>
		<Line>TaskbarSettingsItem.Label=$Menu.Taskbar</Line>
		<Line>TaskbarSettingsItem.Tip=$Menu.TaskbarTip</Line>
		<Line>TaskbarSettingsItem.Icon=shell32.dll,40</Line>
		<Line>ProgramsFeaturesItem.Command=programs_features</Line>
		<Line>ProgramsFeaturesItem.Label=$Menu.Features</Line>
		<Line>ProgramsFeaturesItem.Tip=$Menu.FeaturesTip</Line>
		<Line>ProgramsFeaturesItem.Icon=shell32.dll,271</Line>
		<Line>MenuSettingsItem.Command=menu_settings</Line>
		<Line>MenuSettingsItem.Label=$Menu.ClassicSettings</Line>
		<Line>MenuSettingsItem.Tip=$Menu.SettingsTip</Line>
		<Line>MenuSettingsItem.Icon=,1</Line>
		<Line>SearchMenu.Items=SearchFilesItem,SearchPrinterItem,SearchComputersItem,SearchPeopleItem</Line>
		<Line>SearchMenu.Command=search</Line>
		<Line>SearchMenu.Label=$Menu.Search</Line>
		<Line>SearchMenu.Icon=shell32.dll,323</Line>
		<Line>SearchFilesItem.Command=search_files</Line>
		<Line>SearchFilesItem.Label=$Menu.SearchFiles</Line>
		<Line>SearchFilesItem.Icon=shell32.dll,134</Line>
		<Line>SearchPrinterItem.Command=search_printer</Line>
		<Line>SearchPrinterItem.Label=$Menu.SearchPrinter</Line>
		<Line>SearchPrinterItem.Icon=shell32.dll,1006</Line>
		<Line>SearchComputersItem.Command=search_computers</Line>
		<Line>SearchComputersItem.Label=$Menu.SearchComputers</Line>
		<Line>SearchComputersItem.Icon=shell32.dll,135</Line>
		<Line>SearchPeopleItem.Command=search_people</Line>
		<Line>SearchPeopleItem.Label=$Menu.SearchPeople</Line>
		<Line>SearchPeopleItem.Icon=shell32.dll,269</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.Logoff</Line>
		<Line>LogOffItem.Icon=shell32.dll,325</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Icon=shell32.dll,331</Line>
		<Line>DisconnectItem.Command=disconnect</Line>
		<Line>DisconnectItem.Label=$Menu.Disconnect</Line>
		<Line>DisconnectItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Items=RestartItem,ShutdownItem</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Settings=SPLIT</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Icon=none</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Icon=none</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP|TRACK_RECENT</Line>
	</MenuItems>
	<DisableHotCorner value="DisableAll"/>
	<EnableStartButton value="1"/>
	<StartButtonType value="MetroButton"/>
	<StartButtonPath value="%ProgramW6432%\Classic Shell\\NewStart.png"/>
</Settings>
