<?xml version="1.0"?>
<Settings component="StartMenu" version="4.3.0">
	<MenuStyle value="Classic2"/>
	<Documents value="Show"/>
	<MaxRecentDocuments value="30"/>
	<PinnedPrograms value="FastItems"/>
	<RecentMetroApps value="0"/>
	<MaxRecentPrograms value="20"/>
	<RecentProgsTop value="0"/>
	<RecentSortName value="0"/>
	<RecentProgKeys value="HiddenDigits"/>
	<EnableJumplists value="1"/>
	<MaxJumplists value="30"/>
	<StartScreenShortcut value="0"/>
	<HighlightNew value="0"/>
	<CheckWinUpdates value="0"/>
	<ScrollType value="NoScroll"/>
	<SearchResultsMax value="20"/>
	<SkinC2 value="Smoked Glass"/>
	<SkinVariationC2 value=""/>
	<SkinOptionsC2>
		<Line>NO_ICONS=1</Line>
		<Line>USER_IMAGE=1</Line>
		<Line>USER_NAME=1</Line>
		<Line>CENTER_NAME=1</Line>
		<Line>SMALL_ICONS=1</Line>
		<Line>LARGE_FONT=0</Line>
		<Line>DISABLE_MASK=1</Line>
	</SkinOptionsC2>
	<SkipMetro value="1"/>
	<MenuItems2>
		<Line>Items=COLUMN_PADDING,ProgramsMenu,AppsMenu,SearchBoxItem,COLUMN_BREAK,FavoritesItem,UserFilesItem,UserDocumentsItem,UserPicturesItem,ComputerItem,RecentDocumentsItem,SEPARATOR,ControlPanelItem,PCSettingsItem,SecurityItem,NetworkItem,PrintersItem,SEPARATOR,SearchMenu,HelpItem,RunItem,COLUMN_PADDING,SEPARATOR,ShutdownBoxItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>AppsMenu.Command=apps</Line>
		<Line>AppsMenu.Label=$Menu.Apps</Line>
		<Line>AppsMenu.Icon=,2</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP|TRACK_RECENT</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=$Menu.Favorites</Line>
		<Line>FavoritesItem.Icon=imageres.dll,1024</Line>
		<Line>UserFilesItem.Command=user_files</Line>
		<Line>UserFilesItem.Tip=$Menu.UserFilesTip</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>RecentDocumentsItem.Command=recent_documents</Line>
		<Line>RecentDocumentsItem.Settings=ITEMS_FIRST</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Tip=$Menu.ControlPanelTip</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>ControlPanelItem.Settings=TRACK_RECENT</Line>
		<Line>PCSettingsItem.Command=pc_settings</Line>
		<Line>PCSettingsItem.Label=$Menu.PCSettings</Line>
		<Line>PCSettingsItem.Icon=%windir%\ImmersiveControlPanel\SystemSettings.exe,10</Line>
		<Line>PCSettingsItem.Settings=TRACK_RECENT</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Tip=$Menu.SecurityTip</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>SearchMenu.Items=SearchFilesItem,SearchPrinterItem,SearchComputersItem,SearchPeopleItem</Line>
		<Line>SearchMenu.Command=search</Line>
		<Line>SearchMenu.Label=$Menu.Search</Line>
		<Line>SearchMenu.Icon=shell32.dll,323</Line>
		<Line>SearchFilesItem.Command=search_files</Line>
		<Line>SearchFilesItem.Label=$Menu.SearchFiles</Line>
		<Line>SearchFilesItem.Tip=$Menu.SearchFilesTip</Line>
		<Line>SearchFilesItem.Icon=shell32.dll,134</Line>
		<Line>SearchPrinterItem.Command=search_printer</Line>
		<Line>SearchPrinterItem.Label=$Menu.SearchPrinter</Line>
		<Line>SearchPrinterItem.Tip=$Menu.SearchPrintersTip</Line>
		<Line>SearchPrinterItem.Icon=shell32.dll,1006</Line>
		<Line>SearchComputersItem.Command=search_computers</Line>
		<Line>SearchComputersItem.Label=$Menu.SearchComputers</Line>
		<Line>SearchComputersItem.Tip=$Menu.SearchComputersTip</Line>
		<Line>SearchComputersItem.Icon=shell32.dll,135</Line>
		<Line>SearchPeopleItem.Command=search_people</Line>
		<Line>SearchPeopleItem.Label=$Menu.SearchPeople</Line>
		<Line>SearchPeopleItem.Icon=shell32.dll,269</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Tip=$Menu.HelpTip</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Tip=$Menu.RunTip</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>ShutdownBoxItem.Items=SwitchUserItem,LogOffItem,LockItem,SEPARATOR,SleepItem,HibernateItem,SEPARATOR,RestartNUItem,RestartItem,UndockItem,DisconnectItem,ShutdownNUItem,ShutdownItem</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Settings=SPLIT</Line>
		<Line>SwitchUserItem.Command=switch_user</Line>
		<Line>SwitchUserItem.Label=$Menu.SwitchUser</Line>
		<Line>SwitchUserItem.Tip=$Menu.SwitchUserTip</Line>
		<Line>SwitchUserItem.Icon=none</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.LogOffShort</Line>
		<Line>LogOffItem.Tip=$Menu.LogOffTip</Line>
		<Line>LogOffItem.Icon=none</Line>
		<Line>LockItem.Command=lock</Line>
		<Line>LockItem.Label=$Menu.Lock</Line>
		<Line>LockItem.Tip=$Menu.LockTip</Line>
		<Line>LockItem.Icon=none</Line>
		<Line>SleepItem.Command=sleep</Line>
		<Line>SleepItem.Label=$Menu.Sleep</Line>
		<Line>SleepItem.Tip=$Menu.SleepTip</Line>
		<Line>SleepItem.Icon=none</Line>
		<Line>HibernateItem.Command=hibernate</Line>
		<Line>HibernateItem.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem.Tip=$Menu.HibernateTip</Line>
		<Line>HibernateItem.Icon=none</Line>
		<Line>RestartNUItem.Command=restart_noupdate</Line>
		<Line>RestartNUItem.Label=$Menu.Restart</Line>
		<Line>RestartNUItem.Tip=$Menu.RestartTip</Line>
		<Line>RestartNUItem.Icon=none</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Tip=$Menu.RestartTip</Line>
		<Line>RestartItem.Icon=none</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Tip=$Menu.UndockTip</Line>
		<Line>UndockItem.Icon=none</Line>
		<Line>DisconnectItem.Command=disconnect</Line>
		<Line>DisconnectItem.Label=$Menu.Disconnect</Line>
		<Line>DisconnectItem.Tip=$Menu.DisconnectTip</Line>
		<Line>DisconnectItem.Icon=none</Line>
		<Line>ShutdownNUItem.Command=shutdown_noupdate</Line>
		<Line>ShutdownNUItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownNUItem.Tip=$Menu.ShutdownTip</Line>
		<Line>ShutdownNUItem.Icon=none</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Tip=$Menu.ShutdownTip</Line>
		<Line>ShutdownItem.Icon=none</Line>
	</MenuItems2>
	<EnableExplorer value="0"/>
</Settings>
