<?xml version="1.0"?>
<Settings component="StartMenu" version="4.2.1">
	<MenuStyle value="Classic2"/>
	<MiddleClick value="WindowsMenu"/>
	<Hover value="WindowsMenu"/>
	<ShiftRight value="1"/>
	<Favorites value="Menu"/>
	<Documents value="Menu"/>
	<UserFiles value="Menu"/>
	<UserDocuments value="Menu"/>
	<UserPictures value="Menu"/>
	<ControlPanel value="Menu"/>
	<Network value="Show"/>
	<Printers value="Menu"/>
	<Shutdown value="Menu"/>
	<LogOff value="1"/>
	<ConfirmLogOff value="1"/>
	<HideProgramsMetro value="0"/>
	<MenuDelay value="200"/>
	<InfotipDelay value="40,400"/>
	<SameSizeColumns value="0"/>
	<SearchBox value="Normal"/>
	<SearchAutoComplete value="0"/>
	<MainMenuAnimation value="None"/>
	<SubMenuAnimation value="None"/>
	<AeroGlass value="0"/>
	<SkinC2 value="Classic Skin"/>
	<SkinVariationC2 value=""/>
	<SkinOptionsC2 value="E55CEDD2|C26EAF5D|86F3669D|5225DC47|5D3248DC|E87963C2|80316ABE|"/>
	<EnableStartButton value="1"/>
	<StartButtonType value="ClasicButton"/>
	<SkipMetro value="1"/>
	<OpenMouseMonitor value="1"/>
	<MenuItems2>
		<Line>Items=COLUMN_PADDING,SearchFileEX,SearchBoxItem,SEPARATOR,ProgramsMenu,COLUMN_BREAK,FavoritesItem,DocumentsItem,Printers,SettingsMenu,SearchMenu,HelpItem,RunItem,SEPARATOR,LogOffItem,HibernateItem2,UndockItem,DisconnectItem,SwitchUserItem2,ShutdownBoxItem</Line>
		<Line>SearchFileEX.Command="%ProgramFiles(x86)%\GOFF Concepts\FileSearchEX\FileSearchEX.exe" "%HOMEPATH%"</Line>
		<Line>SearchFileEX.Label=EZ Search</Line>
		<Line>SearchFileEX.Tip=EZ Search Via SearchFileEX</Line>
		<Line>SearchFileEX.Icon=shell32.dll, 23</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=$Menu.Favorites</Line>
		<Line>FavoritesItem.Icon=shell32.dll,322</Line>
		<Line>DocumentsItem.Items=UserFilesItem,UserDocumentsItem,UserPicturesItem</Line>
		<Line>DocumentsItem.Command=recent_documents</Line>
		<Line>DocumentsItem.Label=$Menu.Documents</Line>
		<Line>DocumentsItem.Icon=shell32.dll, 152</Line>
		<Line>DocumentsItem.Settings=ITEMS_FIRST</Line>
		<Line>UserFilesItem.Command=user_files</Line>
		<Line>UserFilesItem.Tip=$Menu.UserFilesTip</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>Printers.Command=printers</Line>
		<Line>Printers.Label=$Menu.Printers</Line>
		<Line>Printers.Tip=$Menu.PrintersTip</Line>
		<Line>Printers.Icon=shell32.dll, 311</Line>
		<Line>Printers.Settings=ITEMS_FIRST</Line>
		<Line>SettingsMenu.Items=ControlPanelItem,SEPARATOR,SecurityItem,NetworkItem,PrintersItem,TaskbarSettingsItem,ProgramsFeaturesItem,SEPARATOR,MenuSettingsItem</Line>
		<Line>SettingsMenu.Command=settings</Line>
		<Line>SettingsMenu.Label=$Menu.Settings</Line>
		<Line>SettingsMenu.Icon=shell32.dll,330</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>TaskbarSettingsItem.Command=taskbar_settings</Line>
		<Line>TaskbarSettingsItem.Label=$Menu.Taskbar</Line>
		<Line>TaskbarSettingsItem.Tip=$Menu.TaskbarTip</Line>
		<Line>TaskbarSettingsItem.Icon=shell32.dll,40</Line>
		<Line>ProgramsFeaturesItem.Command=programs_features</Line>
		<Line>ProgramsFeaturesItem.Label=$Menu.Features</Line>
		<Line>ProgramsFeaturesItem.Tip=$Menu.FeaturesTip</Line>
		<Line>ProgramsFeaturesItem.Icon=shell32.dll,271</Line>
		<Line>MenuSettingsItem.Command=menu_settings</Line>
		<Line>MenuSettingsItem.Label=$Menu.ClassicSettings</Line>
		<Line>MenuSettingsItem.Tip=$Menu.SettingsTip</Line>
		<Line>MenuSettingsItem.Icon=,1</Line>
		<Line>SearchMenu.Items=SearchFilesItem,SearchPrinterItem,SearchComputersItem,SearchPeopleItem</Line>
		<Line>SearchMenu.Command=search</Line>
		<Line>SearchMenu.Label=$Menu.Search</Line>
		<Line>SearchMenu.Icon=shell32.dll,323</Line>
		<Line>SearchFilesItem.Command=search_files</Line>
		<Line>SearchFilesItem.Label=$Menu.SearchFiles</Line>
		<Line>SearchFilesItem.Icon=shell32.dll,134</Line>
		<Line>SearchPrinterItem.Command=search_printer</Line>
		<Line>SearchPrinterItem.Label=$Menu.SearchPrinter</Line>
		<Line>SearchPrinterItem.Icon=shell32.dll,1006</Line>
		<Line>SearchComputersItem.Command=search_computers</Line>
		<Line>SearchComputersItem.Label=$Menu.SearchComputers</Line>
		<Line>SearchComputersItem.Icon=shell32.dll,135</Line>
		<Line>SearchPeopleItem.Command=search_people</Line>
		<Line>SearchPeopleItem.Label=$Menu.SearchPeople</Line>
		<Line>SearchPeopleItem.Icon=shell32.dll,269</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.Logoff</Line>
		<Line>LogOffItem.Icon=shell32.dll,325</Line>
		<Line>HibernateItem2.Command=hibernate</Line>
		<Line>HibernateItem2.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem2.Icon=shell32.dll, 28</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Icon=shell32.dll,331</Line>
		<Line>DisconnectItem.Command=disconnect</Line>
		<Line>DisconnectItem.Label=$Menu.Disconnect</Line>
		<Line>DisconnectItem.Icon=shell32.dll,329</Line>
		<Line>SwitchUserItem2.Command=switch_user</Line>
		<Line>SwitchUserItem2.Label=$Menu.SwitchUser</Line>
		<Line>SwitchUserItem2.Icon=shell32.dll, 16739</Line>
		<Line>ShutdownBoxItem.Items=SwitchUserItem,LockItem,SleepItem,HibernateItem,RestartItem,ShutdownItem</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>SwitchUserItem.Command=switch_user</Line>
		<Line>SwitchUserItem.Label=$Menu.SwitchUser</Line>
		<Line>SwitchUserItem.Icon=none</Line>
		<Line>LockItem.Command=lock</Line>
		<Line>LockItem.Label=$Menu.Lock</Line>
		<Line>LockItem.Icon=none</Line>
		<Line>SleepItem.Command=sleep</Line>
		<Line>SleepItem.Label=$Menu.Sleep</Line>
		<Line>SleepItem.Icon=none</Line>
		<Line>HibernateItem.Command=hibernate</Line>
		<Line>HibernateItem.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem.Icon=none</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Icon=none</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Icon=none</Line>
	</MenuItems2>
	<CascadeAll value="1"/>
	<AllProgramsDelay value="40"/>
	<InitiallySelect value="SelectButton"/>
	<SkinA value="Classic Skin"/>
	<SkinVariationA value=""/>
	<SkinOptionsA value=""/>
	<CascadingMenu value="1"/>
</Settings>
