<?xml version="1.0"?>
<Settings component="StartMenu" version="4.0.2">
	<MenuStyle value="Classic1"/>
	<MouseClick value="ClassicMenu"/>
	<ShiftClick value="Nothing"/>
	<WinKey value="Nothing"/>
	<ShiftWin value="Nothing"/>
	<Hover value="ClassicMenu"/>
	<StartHoverDelay value="78"/>
	<ShiftRight value="0"/>
	<Documents value="Hide"/>
	<MaxRecentDocuments value="0"/>
	<UserFiles value="Show"/>
	<UserDocuments value="Show"/>
	<Shutdown value="Menu"/>
	<LogOff value="0"/>
	<Undock value="0"/>
	<Help value="0"/>
	<RecentPrograms value="None"/>
	<EnableJumplists value="0"/>
	<StartScreenShortcut value="0"/>
	<HighlightNew value="0"/>
	<CheckWinUpdates value="0"/>
	<MenuDelay value="89"/>
	<InfotipDelay value="0,0"/>
	<ScrollType value="Auto"/>
	<EnableAccessibility value="1"/>
	<SearchBox value="Normal"/>
	<SmallIconSize value="16"/>
	<LargeIconSize value="28"/>
	<MaxMenuWidth value="60"/>
	<MainMenuAnimation value="None"/>
	<MenuCaption value="Across my memory"/>
	<NumericSort value="1"/>
	<NoTaskbarTransparency2 value="0"/>
	<SkinC1 value="My Skin With Fixed Font type"/>
	<SkinVariationC1 value=""/>
	<SkinOptionsC1 value="DA60029A|BD80CDB3|C26EAF5C|86F3669C|5225DC46|5D3248DC|1FC64125|0663DC39|"/>
	<EnableStartButton value="1"/>
	<StartButtonType value="AeroButton"/>
	<StartButtonSize value="0"/>
	<SkipMetro value="1"/>
	<DisableHotCorner value="DisableAll"/>
	<MenuItems1>
		<Line>Items=COLUMN_PADDING,ProgramsMenu,COLUMN_BREAK,FavoritesItem,DocumentsItem,SettingsMenu,SearchMenu,HelpItem,RunItem,SEPARATOR,UndockItem,DisconnectItem,ShutdownBoxItem,SearchBoxItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=$Menu.Favorites</Line>
		<Line>FavoritesItem.Icon=shell32.dll,322</Line>
		<Line>FavoritesItem.Settings=NOTRACK_RECENT</Line>
		<Line>DocumentsItem.Items=UserFilesItem,UserDocumentsItem,UserPicturesItem</Line>
		<Line>DocumentsItem.Command=recent_documents</Line>
		<Line>DocumentsItem.Label=$Menu.Documents</Line>
		<Line>DocumentsItem.Icon=shell32.dll,327</Line>
		<Line>DocumentsItem.Settings=ITEMS_FIRST</Line>
		<Line>UserFilesItem.Command=user_files</Line>
		<Line>UserFilesItem.Tip=$Menu.UserFilesTip</Line>
		<Line>UserFilesItem.Settings=NOTRACK_RECENT</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>UserDocumentsItem.Settings=NOTRACK_RECENT</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>UserPicturesItem.Settings=NOTRACK_RECENT</Line>
		<Line>SettingsMenu.Items=ControlPanelItem,SEPARATOR,SecurityItem</Line>
		<Line>SettingsMenu.Command=settings</Line>
		<Line>SettingsMenu.Label=$Menu.Settings</Line>
		<Line>SettingsMenu.Icon=shell32.dll,330</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>SearchMenu.Items=SearchFilesItem,SearchPrinterItem,SearchComputersItem</Line>
		<Line>SearchMenu.Command="%SystemDrive%\Program Files\Toolz\xsearch.exe"</Line>
		<Line>SearchMenu.Label=$Menu.Search</Line>
		<Line>SearchMenu.Icon=shell32.dll,323</Line>
		<Line>SearchFilesItem.Command="%SystemDrive%\Program Files\Toolz\xsearch.exe"</Line>
		<Line>SearchFilesItem.Label=$Menu.SearchFiles</Line>
		<Line>SearchFilesItem.Icon=shell32.dll,134</Line>
		<Line>SearchPrinterItem.Command=search_printer</Line>
		<Line>SearchPrinterItem.Label=$Menu.SearchPrinter</Line>
		<Line>SearchPrinterItem.Icon=shell32.dll,1006</Line>
		<Line>SearchComputersItem.Command=search_computers</Line>
		<Line>SearchComputersItem.Label=$Menu.SearchComputers</Line>
		<Line>SearchComputersItem.Icon=shell32.dll,135</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Icon=shell32.dll,331</Line>
		<Line>DisconnectItem.Command=disconnect</Line>
		<Line>DisconnectItem.Label=$Menu.Disconnect</Line>
		<Line>DisconnectItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Items=RestartItem,LockItem,ShutdownItem,SleepItem,LogOffItem,HibernateItem</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Icon=none</Line>
		<Line>LockItem.Command="%SystemDrive%\Program Files\Toolz\DeskLock.exe"</Line>
		<Line>LockItem.Label=$Menu.Lock</Line>
		<Line>LockItem.Icon=none</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Icon=none</Line>
		<Line>SleepItem.Command=sleep</Line>
		<Line>SleepItem.Label=$Menu.Sleep</Line>
		<Line>SleepItem.Icon=none</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.Logoff</Line>
		<Line>LogOffItem.Icon=shell32.dll,325</Line>
		<Line>HibernateItem.Command=hibernate</Line>
		<Line>HibernateItem.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem.Icon=none</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP|TRACK_RECENT</Line>
	</MenuItems1>
	<SkinA value="&lt;No Skin&gt;"/>
	<SkinVariationA value=""/>
	<SkinOptionsA value=""/>
	<EnableExit value="1"/>
</Settings>
