<?xml version="1.0"?>
<Settings component="StartMenu" version="4.0.2">
	<MenuStyle value="Classic1"/>
	<MiddleClick value="WindowsMenu"/>
	<ShiftRight value="0"/>
	<Computer value="Hide"/>
	<Favorites value="Hide"/>
	<UserFiles value="Hide"/>
	<UserDocuments value="Hide"/>
	<UserPictures value="Hide"/>
	<Printers value="Hide"/>
	<Shutdown value="Menu"/>
	<LogOff value="1"/>
	<Undock value="0"/>
	<Search value="0"/>
	<RecentPrograms value="None"/>
	<HighlightNew value="0"/>
	<CheckWinUpdates value="0"/>
	<SearchSelect value="0"/>
	<SearchTrack value="0"/>
	<SearchPrograms value="1"/>
	<SearchFiles value="1"/>
	<SearchInternet value="0"/>
	<FontSmoothing value="Default"/>
	<MenuShadow value="0"/>
	<SkinC1 value="Classic Skin"/>
	<SkinVariationC1 value=""/>
	<SkinOptionsC1 value="BD80CDB3|C26EAF5C|86F3669C|5225DC46|5D3248DC|E87963C3|80316ABF|"/>
	<EnableStartButton value="1"/>
	<StartButtonType value="ClasicButton"/>
	<StartButtonPath value=""/>
	<StartButtonSize value="0"/>
	<StartButtonIcon value="%SystemRoot%\System32\winver.exe, 1"/>
	<StartButtonText value="$Menu.Start"/>
	<MenuItems1>
		<Line>Items=COLUMN_PADDING,ProgramsMenu,COLUMN_BREAK,DocumentsItem,ComputerItem,SettingsMenu,HelpItem,RunItem,SEPARATOR,SearchBoxItem,SEPARATOR,ShutdownBoxItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>DocumentsItem.Items=UserFilesItem,UserDocumentsItem,UserPicturesItem</Line>
		<Line>DocumentsItem.Command=recent_documents</Line>
		<Line>DocumentsItem.Label=$Menu.Documents</Line>
		<Line>DocumentsItem.Icon=shell32.dll,327</Line>
		<Line>DocumentsItem.Settings=ITEMS_FIRST</Line>
		<Line>UserFilesItem.Command=user_files</Line>
		<Line>UserFilesItem.Tip=$Menu.UserFilesTip</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>SettingsMenu.Items=ControlPanelItem,SEPARATOR,SecurityItem,NetworkItem,PrintersItem,TaskbarSettingsItem,ProgramsFeaturesItem</Line>
		<Line>SettingsMenu.Command=settings</Line>
		<Line>SettingsMenu.Label=$Menu.Settings</Line>
		<Line>SettingsMenu.Icon=shell32.dll,330</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>TaskbarSettingsItem.Command=taskbar_settings</Line>
		<Line>TaskbarSettingsItem.Label=$Menu.Taskbar</Line>
		<Line>TaskbarSettingsItem.Tip=$Menu.TaskbarTip</Line>
		<Line>TaskbarSettingsItem.Icon=shell32.dll,40</Line>
		<Line>ProgramsFeaturesItem.Command=programs_features</Line>
		<Line>ProgramsFeaturesItem.Label=$Menu.Features</Line>
		<Line>ProgramsFeaturesItem.Tip=$Menu.FeaturesTip</Line>
		<Line>ProgramsFeaturesItem.Icon=shell32.dll,271</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP</Line>
		<Line>ShutdownBoxItem.Items=ShutdownItem,HibernateItem,SleepItem,LogOffItem,RestartItem</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=%USERPROFILE%\Documents\My Icons\ShutDown.ico</Line>
		<Line>ShutdownBoxItem.Settings=INLINE</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Icon=%USERPROFILE%\Documents\My Icons\ShutDown.ico</Line>
		<Line>HibernateItem.Command=hibernate</Line>
		<Line>HibernateItem.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem.Icon=%USERPROFILE%\Documents\My Icons\Hibernation.ico</Line>
		<Line>SleepItem.Command=sleep</Line>
		<Line>SleepItem.Label=מצב המתנה</Line>
		<Line>SleepItem.Icon=%USERPROFILE%\Documents\My Icons\StandBy.ico</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.Logoff</Line>
		<Line>LogOffItem.Icon=%USERPROFILE%\Documents\My Icons\LogOff.ico</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Icon=%USERPROFILE%\Documents\My Icons\Restart.ico</Line>
	</MenuItems1>
	<CascadeAll value="0"/>
	<SkinA value="Classic Skin"/>
	<SkinVariationA value=""/>
	<SkinOptionsA value="E87963C3|80316ABF|"/>
	<CascadingMenu value="0"/>
	<ShowNewFolder value="1"/>
	<EnableExit value="1"/>
	<EnableExplorer value="1"/>
</Settings>
