<?xml version="1.0"?>
<Settings component="StartMenu" version="3.6.5">
	<DefaultMenuStyle value="Classic"/>
	<MouseClick value="WindowsMenu"/>
	<ShiftClick value="WindowsMenu"/>
	<WinKey value="WindowsMenu"/>
	<ShiftWin value="Nothing"/>
	<MiddleClick value="Nothing"/>
	<Favorites value="Hide"/>
	<Documents value="Hide"/>
	<UserFiles value="Hide"/>
	<UserDocuments value="Show"/>
	<UserPictures value="Hide"/>
	<Search value="0"/>
	<Help value="0"/>
	<Run value="0"/>
	<LogOff value="0"/>
	<RecentPrograms value="0"/>
	<MainMenuAnimation value="None"/>
	<EnableJumplists value="0"/>
	<EnableAccessibility value="0"/>
	<DelayIcons value="0"/>
	<ScrollType value="Scroll"/>
	<MenuCaption value="Windows 7 Ultimate SP1 x64"/>
	<SearchBox value="Normal"/>
	<SearchTrack value="1"/>
	<Skin1 value="&lt;No Skin&gt;"/>
	<SkinVariation1 value=""/>
	<SkinOptions1 value=""/>
	<CascadingMenu value="1"/>
	<EnableExplorer value="0"/>
	<CascadeAll value="1"/>
	<AllProgramsDelay value="50"/>
	<InitiallySelect value="SelectSearch"/>
	<Skin2 value="&lt;No Skin&gt;"/>
	<SkinVariation2 value=""/>
	<SkinOptions2 value=""/>
	<EnableStartButton value="1"/>
	<StartButtonType value="CustomButton"/>
	<StartButtonPath value="D:\Documents\Documents\Modified\jalt-2\explorer.exe\6801.png"/>
	<StartButtonSize value="0"/>
</Settings>
