<?xml version="1.0"?>
<Settings component="StartMenu" version="4.3.0">
	<MenuStyle value="Win7"/>
	<ShiftRight value="1"/>
	<SortRecentDocuments value="Date"/>
	<Undock value="0"/>
	<ShowAppsMenu value="0"/>
	<Help value="0"/>
	<AllProgramsMetro value="0"/>
	<OpenPrograms value="0"/>
	<ProgramsMenuDelay value="200"/>
	<PinnedPrograms value="FastItems"/>
	<RecentPrograms value="Frequent"/>
	<RecentMetroApps value="0"/>
	<MaxRecentPrograms value="15"/>
	<RecentProgsTop value="0"/>
	<RecentProgKeys value="Normal"/>
	<HybridShutdown value="0"/>
	<ProgramsWidth value="45"/>
	<StartScreenShortcut value="0"/>
	<HighlightNew value="0"/>
	<CheckWinUpdates value="0"/>
	<MenuDelay value="200"/>
	<EnableDragDrop value="0"/>
	<DelayIcons value="0"/>
	<SearchMetroApps value="0"/>
	<SearchInternet value="0"/>
	<SubMenuAnimation value="None"/>
	<FontSmoothing value="ClearType"/>
	<SkinW7 value="Windows Aero"/>
	<SkinVariationW7 value=""/>
	<SkinOptionsW7>
		<Line>USER_IMAGE=1</Line>
		<Line>SMALL_ICONS=0</Line>
		<Line>LARGE_FONT=1</Line>
		<Line>DISABLE_MASK=1</Line>
		<Line>WHITE_SUBMENUS=1</Line>
	</SkinOptionsW7>
	<EnableStartButton value="0"/>
	<StartButtonType value="AeroButton"/>
	<SkipMetro value="1"/>
	<DisableHotCorner value="DisableAll"/>
	<MenuItems7>
		<Line>Item1.Command=user_files</Line>
		<Line>Item1.Settings=ITEM_DISABLED</Line>
		<Line>Item2.Command=user_documents</Line>
		<Line>Item2.Settings=NOEXPAND</Line>
		<Line>Item3.Command=user_pictures</Line>
		<Line>Item3.Settings=NOEXPAND</Line>
		<Line>Item4.Command=user_music</Line>
		<Line>Item4.Settings=NOEXPAND</Line>
		<Line>Item5.Command=user_videos</Line>
		<Line>Item5.Settings=NOEXPAND</Line>
		<Line>Item6.Command=downloads</Line>
		<Line>Item6.Settings=NOEXPAND</Line>
		<Line>Item7.Command=homegroup</Line>
		<Line>Item7.Settings=ITEM_DISABLED</Line>
		<Line>Item8.Command=separator</Line>
		<Line>Item9.Command=games</Line>
		<Line>Item9.Settings=TRACK_RECENT|ITEM_DISABLED</Line>
		<Line>Item10.Command=favorites</Line>
		<Line>Item10.Settings=ITEM_DISABLED</Line>
		<Line>Item11.Command=recent_documents</Line>
		<Line>Item12.Command=computer</Line>
		<Line>Item12.Settings=NOEXPAND</Line>
		<Line>Item13.Command=network</Line>
		<Line>Item14.Command=network_connections</Line>
		<Line>Item14.Settings=ITEM_DISABLED</Line>
		<Line>Item15.Command=separator</Line>
		<Line>Item16.Command=control_panel</Line>
		<Line>Item16.Settings=TRACK_RECENT|NOEXPAND</Line>
		<Line>Item17.Command=pc_settings</Line>
		<Line>Item17.Label=$Menu.PCSettings</Line>
		<Line>Item17.Icon=%windir%\ImmersiveControlPanel\SystemSettings.exe,10</Line>
		<Line>Item17.Settings=TRACK_RECENT</Line>
		<Line>Item18.Command=devices</Line>
		<Line>Item18.Settings=NOEXPAND</Line>
		<Line>Item19.Command=defaults</Line>
		<Line>Item20.Command=help</Line>
		<Line>Item20.Settings=ITEM_DISABLED</Line>
		<Line>Item21.Command=run</Line>
		<Line>Item22.Command=apps</Line>
		<Line>Item22.Settings=ITEM_DISABLED</Line>
		<Line>Item23.Command=windows_security</Line>
	</MenuItems7>
	<ShowNewFolder value="0"/>
	<EnableExit value="0"/>
	<EnableExplorer value="1"/>
</Settings>
