<?xml version="1.0"?>
<Settings component="StartMenu" version="3.6.8">
	<DefaultMenuStyle value="Classic"/>
	<MiddleClick value="WindowsMenu"/>
	<Computer value="Hide"/>
	<Favorites value="Hide"/>
	<UserFiles value="Hide"/>
	<UserDocuments value="Hide"/>
	<UserPictures value="Hide"/>
	<Printers value="Hide"/>
	<Shutdown value="Menu"/>
	<LogOff value="1"/>
	<RecentPrograms value="0"/>
	<FontSmoothing value="Default"/>
	<MenuShadow value="0"/>
	<Skin1 value="Classic Skin"/>
	<SkinVariation1 value=""/>
	<SkinOptions1 value="DA60029A|E55CEDD2|BD80CDB3|C26EAF5C|86F3669C|5225DC46|5D3248DC|E87963C3|80316ABF|"/>
	<ShowNewFolder value="1"/>
	<EnableExit value="0"/>
	<EnableExplorer value="1"/>
	<MenuItems>
		<Line>Items=COLUMN_PADDING,ProgramsMenu,AppsMenu,COLUMN_BREAK,FavoritesItem,DocumentsItem,ComputerItem,SettingsMenu,HelpItem,RunItem,SEPARATOR,UndockItem,DisconnectItem,SearchBoxItem,SEPARATOR,ShutdownBoxItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>AppsMenu.Command=apps</Line>
		<Line>AppsMenu.Label=$Menu.Apps</Line>
		<Line>AppsMenu.Icon=shell32.dll,326</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=$Menu.Favorites</Line>
		<Line>FavoritesItem.Icon=shell32.dll,322</Line>
		<Line>DocumentsItem.Items=UserFilesItem,UserDocumentsItem,UserPicturesItem</Line>
		<Line>DocumentsItem.Command=documents</Line>
		<Line>DocumentsItem.Label=$Menu.Documents</Line>
		<Line>DocumentsItem.Icon=shell32.dll,327</Line>
		<Line>DocumentsItem.Settings=ITEMS_FIRST</Line>
		<Line>UserFilesItem.Command=user_files</Line>
		<Line>UserFilesItem.Tip=$Menu.UserFilesTip</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>SettingsMenu.Items=ControlPanelItem,SEPARATOR,SecurityItem,NetworkItem,PrintersItem,TaskbarSettingsItem,ProgramsFeaturesItem,SEPARATOR,MenuSettingsItem</Line>
		<Line>SettingsMenu.Command=settings</Line>
		<Line>SettingsMenu.Label=$Menu.Settings</Line>
		<Line>SettingsMenu.Icon=shell32.dll,330</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>TaskbarSettingsItem.Command=taskbar_settings</Line>
		<Line>TaskbarSettingsItem.Label=$Menu.Taskbar</Line>
		<Line>TaskbarSettingsItem.Tip=$Menu.TaskbarTip</Line>
		<Line>TaskbarSettingsItem.Icon=shell32.dll,40</Line>
		<Line>ProgramsFeaturesItem.Command=programs_features</Line>
		<Line>ProgramsFeaturesItem.Label=$Menu.Features</Line>
		<Line>ProgramsFeaturesItem.Tip=$Menu.FeaturesTip</Line>
		<Line>ProgramsFeaturesItem.Icon=shell32.dll,271</Line>
		<Line>MenuSettingsItem.Command=menu_settings</Line>
		<Line>MenuSettingsItem.Label=$Menu.ClassicSettings</Line>
		<Line>MenuSettingsItem.Tip=$Menu.SettingsTip</Line>
		<Line>MenuSettingsItem.Icon=,1</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Icon=shell32.dll,331</Line>
		<Line>DisconnectItem.Command=disconnect</Line>
		<Line>DisconnectItem.Label=$Menu.Disconnect</Line>
		<Line>DisconnectItem.Icon=shell32.dll,329</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP|TRACK_RECENT</Line>
		<Line>ShutdownBoxItem.Items=ShutdownItem,HibernateItem,SleepItem,LogOffItem,RestartItem</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=%USERPROFILE%\Documents\My Icons\ShutDown.ico</Line>
		<Line>ShutdownBoxItem.Settings=INLINE</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Icon=%USERPROFILE%\Documents\My Icons\ShutDown.ico</Line>
		<Line>HibernateItem.Command=hibernate</Line>
		<Line>HibernateItem.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem.Icon=%USERPROFILE%\Documents\My Icons\Hibernation.ico</Line>
		<Line>SleepItem.Command=sleep</Line>
		<Line>SleepItem.Label=מצב המתנה</Line>
		<Line>SleepItem.Icon=%USERPROFILE%\Documents\My Icons\StandBy.ico</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.Logoff</Line>
		<Line>LogOffItem.Icon=%USERPROFILE%\Documents\My Icons\LogOff.ico</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Icon=%USERPROFILE%\Documents\My Icons\Restart.ico</Line>
	</MenuItems>
	<Skin2 value="Classic Skin"/>
	<SkinVariation2 value=""/>
	<SkinOptions2 value="E87963C3|80316ABF|"/>
	<EnableStartButton value="0"/>
	<StartButtonType value="AeroButton"/>
</Settings>
