<?xml version="1.0"?>
<Settings component="StartMenu" version="4.0.2">
	<MenuStyle value="Classic2"/>
	<ShiftClick value="ClassicMenu"/>
	<ShiftWin value="Nothing"/>
	<Network value="Menu"/>
	<Shutdown value="Menu"/>
	<LogOff value="1"/>
	<Undock value="0"/>
	<PinnedPrograms value="PinnedItems"/>
	<RecentPrograms value="Recent"/>
	<MaxRecentPrograms value="10"/>
	<RecentProgsTop value="1"/>
	<RecentProgKeys value="Normal"/>
	<EnableJumplists value="0"/>
	<JumplistKeys value="Run"/>
	<CheckWinUpdates value="0"/>
	<MaxMainMenuWidth value="20"/>
	<SkinC2 value="Windows Aero"/>
	<SkinVariationC2 value=""/>
	<SkinOptionsC2 value="E55CEDD3|C26EAF5C|86F3669C|5225DC46|5D3248DC|1FC64124|5EA361A2|0663DC39|"/>
	<MenuItems2>
		<Line>Items=COLUMN_PADDING,ProgramsMenu,SearchBoxItem,COLUMN_BREAK,UserFilesItem,SEPARATOR,FavoritesItem,UserDocumentsItem,DocumentsItem,UserPicturesItem,UserMusicItem,SEPARATOR,ComputerItem,ControlPanelItem,NetworkConnectionsItem,NetworkItem,SEPARATOR,HelpItem,DefaultProgramsItem,PrintersItem,RunItem,COLUMN_PADDING,SEPARATOR,COLUMN_BREAK,DisconnectItem,ShutdownBoxItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>ProgramsMenu.Settings=TRACK_RECENT</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>UserFilesItem.Command=user_files</Line>
		<Line>UserFilesItem.Tip=$Menu.UserFilesTip</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=$Menu.Favorites</Line>
		<Line>FavoritesItem.Icon=shell32.dll,322</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>DocumentsItem.Command=recent_documents</Line>
		<Line>DocumentsItem.Label=My Recent Documents</Line>
		<Line>DocumentsItem.Icon=shell32.dll,327</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>UserMusicItem.Link=Music | ::{031E4825-7B94-4DC3-B131-E946B44C8DD5}\Music.library-ms</Line>
		<Line>UserMusicItem.Label=My Music</Line>
		<Line>UserMusicItem.Tip=Contains music files.</Line>
		<Line>UserMusicItem.Settings=NOEXPAND</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>ComputerItem.Label=Computer</Line>
		<Line>ComputerItem.Tip=Gives access to, and information about, the disk drives, cameras, scanners, and other hardware connected to your computer.</Line>
		<Line>ComputerItem.Icon=shell32.dll, 16</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Tip=Provides options for you to customize the appearance and functionality of your computer, add or remove programs, and set up network connections and user accounts.</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>NetworkConnectionsItem.Items=AllNetworkConnectionsItem</Line>
		<Line>NetworkConnectionsItem.Command=network_connections</Line>
		<Line>NetworkConnectionsItem.Label=Connect To</Line>
		<Line>NetworkConnectionsItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkConnectionsItem.Icon=shell32.dll,257</Line>
		<Line>AllNetworkConnectionsItem.Command=control ncpa.cpl</Line>
		<Line>AllNetworkConnectionsItem.Label=Show all connections</Line>
		<Line>AllNetworkConnectionsItem.Tip=$Menu.NetworkTip</Line>
		<Line>AllNetworkConnectionsItem.Icon=shell32.dll,257</Line>
		<Line>NetworkItem.Command=%windir%\explorer.exe /e,::{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}</Line>
		<Line>NetworkItem.Label=Network Places</Line>
		<Line>NetworkItem.Tip=Gives access to, and informations about, folders and files on other computers.</Line>
		<Line>NetworkItem.Icon=shell32.dll,269</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Tip=Opens a central location for Help topics, tutorials, troubleshooting, and other support services.</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>DefaultProgramsItem.Command=control /name Microsoft.DefaultPrograms</Line>
		<Line>DefaultProgramsItem.Label=Default Programs</Line>
		<Line>DefaultProgramsItem.Tip=Choose which programs you want Windows to use for activities like web browsing, editing photos, sending e-mail, and playing music.</Line>
		<Line>DefaultProgramsItem.Icon=shell32.dll, 271</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Tip=Opens a program, folder, document, or a Web site.</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>DisconnectItem.Command=disconnect</Line>
		<Line>DisconnectItem.Label=$Menu.Disconnect</Line>
		<Line>DisconnectItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Items=LogOffItem,SwitchUserItem,LockItem,UndockItem,SleepItem,HibernateItem,RestartItem,ShutdownItem,COLUMN_BREAK</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.Logoff</Line>
		<Line>LogOffItem.Icon=none</Line>
		<Line>SwitchUserItem.Command=switch_user</Line>
		<Line>SwitchUserItem.Label=$Menu.SwitchUser</Line>
		<Line>SwitchUserItem.Icon=none</Line>
		<Line>LockItem.Command=lock</Line>
		<Line>LockItem.Label=$Menu.Lock</Line>
		<Line>LockItem.Icon=none</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Icon=none</Line>
		<Line>SleepItem.Command=sleep</Line>
		<Line>SleepItem.Label=$Menu.Sleep</Line>
		<Line>SleepItem.Icon=none</Line>
		<Line>HibernateItem.Command=hibernate</Line>
		<Line>HibernateItem.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem.Icon=none</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Icon=none</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Icon=none</Line>
	</MenuItems2>
	<InitiallySelect value="SelectSearch"/>
	<ShowNewFolder value="0"/>
	<EnableExit value="0"/>
</Settings>
