<?xml version="1.0"?>
<Settings component="StartMenu" version="3.6.8">
	<DefaultMenuStyle value="XP"/>
	<Hover value="Nothing"/>
	<MaxRecentDocuments value="20"/>
	<SortRecentDocuments value="Date"/>
	<Shutdown value="Menu"/>
	<Search value="1"/>
	<LogOff value="1"/>
	<MaxRecentPrograms value="6"/>
	<RecentProgsTop value="0"/>
	<RecentProgKeys value="NoKey"/>
	<SubMenuAnimation value="None"/>
	<EnableJumplists value="0"/>
	<ScrollType value="Scroll"/>
	<MenuCaption value="Windows 8 Professional"/>
	<MenuUsername value="A N"/>
	<FontSmoothing value="ClearType"/>
	<MenuShadow value="0"/>
	<SearchBox value="Hide"/>
	<Skin1 value="Windows 8 Nerius Black"/>
	<SkinVariation1 value="Less Transparent"/>
	<SkinOptions1 value="DA60029B|E55CEDD3|C26EAF5C|86F3669C|5225DC46|5D3248DC|1FC64125|B8B3A026|7565F33C|07537A24|2E07FDF5|"/>
	<CascadingMenu value="0"/>
	<MenuItems>
		<Line>Items=COLUMN_PADDING,ProgramsMenu,CustomItem2,SearchBoxItem,COLUMN_BREAK,UserDocumentsItem,DocumentsItem,UserPicturesItem,SEPARATOR,ComputerItem,SEPARATOR,AppsMenu,ControlPanelItem,ProgramsFeaturesItem,SecurityItem,NetworkItem,SettingsMenu,PrintersItem,System,SEPARATOR,Administrationsverktyg,HelpItem,Everything,SearchMenu,RunItem,CustomItem3,COLUMN_PADDING,SEPARATOR,ShutdownBoxItem,SEPARATOR</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll, 52</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP|TRACK_RECENT</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>DocumentsItem.Command=documents</Line>
		<Line>DocumentsItem.Settings=ITEMS_FIRST|TRACK_RECENT</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>AppsMenu.Command=apps</Line>
		<Line>AppsMenu.Label=$Menu.Apps</Line>
		<Line>AppsMenu.Icon=shell32.dll,326</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>ProgramsFeaturesItem.Command=programs_features</Line>
		<Line>ProgramsFeaturesItem.Label=$Menu.Features</Line>
		<Line>ProgramsFeaturesItem.Tip=$Menu.FeaturesTip</Line>
		<Line>ProgramsFeaturesItem.Icon=shell32.dll,271</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>SettingsMenu.Command=%SystemRoot%\GodMode.{ED7BA470-8E54-465E-825C-99712043E01C}</Line>
		<Line>SettingsMenu.Label=$Menu.Settings</Line>
		<Line>SettingsMenu.Icon=shell32.dll,330</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>System.Command=apps</Line>
		<Line>System.Link=%SystemRoot%\System32\SystemPropertiesComputerName.exe</Line>
		<Line>System.Label=System</Line>
		<Line>System.Tip=System</Line>
		<Line>System.Settings=OPEN_UP</Line>
		<Line>Administrationsverktyg.Command=menu_settings</Line>
		<Line>Administrationsverktyg.Link=%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Administrative Tools</Line>
		<Line>Administrationsverktyg.Label=Administrationsverktyg</Line>
		<Line>Administrationsverktyg.Settings=OPEN_UP_CHILDREN|TRACK_RECENT</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>Everything.Command="%SystemDrive%\Program Files (x86)\Everything\Everything.exe"</Line>
		<Line>Everything.Link=%SystemDrive%\Program Files (x86)\Everything\Everything.exe</Line>
		<Line>Everything.Label=Sök efter filer</Line>
		<Line>Everything.Settings=TRACK_RECENT</Line>
		<Line>SearchMenu.Items=SearchFilesItem,SearchPrinterItem,SearchComputersItem,SearchPeopleItem</Line>
		<Line>SearchMenu.Command=search</Line>
		<Line>SearchMenu.Label=$Menu.Search</Line>
		<Line>SearchMenu.Icon=shell32.dll,323</Line>
		<Line>SearchFilesItem.Command=search_files</Line>
		<Line>SearchFilesItem.Label=$Menu.SearchFiles</Line>
		<Line>SearchFilesItem.Icon=shell32.dll,134</Line>
		<Line>SearchPrinterItem.Command=search_printer</Line>
		<Line>SearchPrinterItem.Label=$Menu.SearchPrinter</Line>
		<Line>SearchPrinterItem.Icon=shell32.dll,1006</Line>
		<Line>SearchComputersItem.Command=search_computers</Line>
		<Line>SearchComputersItem.Label=$Menu.SearchComputers</Line>
		<Line>SearchComputersItem.Icon=shell32.dll,135</Line>
		<Line>SearchPeopleItem.Command=search_people</Line>
		<Line>SearchPeopleItem.Label=$Menu.SearchPeople</Line>
		<Line>SearchPeopleItem.Icon=shell32.dll,269</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>ShutdownBoxItem.Items=SwitchUserItem,LogOffItem,LockItem,SEPARATOR,SleepItem,HibernateItem,SEPARATOR,RestartItem,UndockItem,DisconnectItem,ShutdownItem</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Settings=SPLIT</Line>
		<Line>SwitchUserItem.Command=switch_user</Line>
		<Line>SwitchUserItem.Label=$Menu.SwitchUser</Line>
		<Line>SwitchUserItem.Icon=none</Line>
		<Line>SwitchUserItem.Settings=INLINE</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.LogoffShort</Line>
		<Line>LogOffItem.Icon=none</Line>
		<Line>LockItem.Command=lock</Line>
		<Line>LockItem.Label=$Menu.Lock</Line>
		<Line>LockItem.Icon=none</Line>
		<Line>SleepItem.Command=sleep</Line>
		<Line>SleepItem.Label=$Menu.Sleep</Line>
		<Line>SleepItem.Icon=none</Line>
		<Line>HibernateItem.Command=hibernate</Line>
		<Line>HibernateItem.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem.Icon=none</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Icon=shell32.dll, 53</Line>
		<Line>RestartItem.Settings=SPLIT</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Icon=none</Line>
		<Line>DisconnectItem.Command=disconnect</Line>
		<Line>DisconnectItem.Label=$Menu.Disconnect</Line>
		<Line>DisconnectItem.Icon=none</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Icon=none</Line>
	</MenuItems>
	<DisableHotCorner value="DisableStart"/>
	<EnableStartButton value="1"/>
	<StartButtonType value="CustomButton"/>
	<StartButtonPath value="%SystemDrive%\Program Files\Classic Shell\Skins\PowerFinal12.png"/>
	<StartButtonSize value="58"/>
	<NoTaskbarTransparency2 value="1"/>
</Settings>
