<?xml version="1.0"?>
<Settings component="StartMenu" version="3.6.5">
	<Computer value="Hide"/>
	<Documents value="Hide"/>
	<UserFiles value="Hide"/>
	<UserDocuments value="Hide"/>
	<UserPictures value="Hide"/>
	<ControlPanel value="Show"/>
	<Shutdown value="Show"/>
	<Search value="1"/>
	<Help value="0"/>
	<LogOff value="0"/>
	<ConfirmLogOff value="1"/>
	<Undock value="1"/>
	<RecentPrograms value="0"/>
	<InfotipDelay value="0,0"/>
	<MainMenuAnimation value="None"/>
	<SubMenuAnimation value="None"/>
	<EnableJumplists value="0"/>
	<PreCacheIcons value="1"/>
	<SameSizeColumns value="0"/>
	<SmallIconSize value="18"/>
	<LargeIconSize value="18"/>
	<SearchBox value="Hide"/>
	<Skin1 value="Classic Skin"/>
	<SkinVariation1 value=""/>
	<SkinOptions1 value="DA60029A|E55CEDD2|BD80CDB2|C26EAF5C|86F3669C|5225DC46|5D3248DD|E87963C3|80316ABF|"/>
	<EnableExit value="1"/>
	<MenuItems>
		<Line>Items=ProgramsMenu,SettingsMenu,SearchMenu,RunItem,SEPARATOR,UndockItem,ShutdownBoxItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>SettingsMenu.Items=ControlPanelItem,SEPARATOR,NetworkItem,PrintersItem,TaskbarSettingsItem</Line>
		<Line>SettingsMenu.Command=settings</Line>
		<Line>SettingsMenu.Label=$Menu.Settings</Line>
		<Line>SettingsMenu.Icon=shell32.dll,330</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>TaskbarSettingsItem.Command=taskbar_settings</Line>
		<Line>TaskbarSettingsItem.Label=$Menu.Taskbar</Line>
		<Line>TaskbarSettingsItem.Tip=$Menu.TaskbarTip</Line>
		<Line>TaskbarSettingsItem.Icon=shell32.dll,40</Line>
		<Line>SearchMenu.Items=SearchFilesItem,SearchPrinterItem,SearchComputersItem</Line>
		<Line>SearchMenu.Command=search</Line>
		<Line>SearchMenu.Label=$Menu.Search</Line>
		<Line>SearchMenu.Icon=%SystemDrive%\Program Files\Icons\Search.ico</Line>
		<Line>SearchFilesItem.Command=search_files</Line>
		<Line>SearchFilesItem.Label=$Menu.SearchFiles</Line>
		<Line>SearchFilesItem.Icon=shell32.dll,134</Line>
		<Line>SearchPrinterItem.Command=search_printer</Line>
		<Line>SearchPrinterItem.Label=$Menu.SearchPrinter</Line>
		<Line>SearchPrinterItem.Icon=shell32.dll,1006</Line>
		<Line>SearchComputersItem.Command=search_computers</Line>
		<Line>SearchComputersItem.Label=$Menu.SearchComputers</Line>
		<Line>SearchComputersItem.Icon=shell32.dll,135</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Icon=%SystemDrive%\Program Files\Icons\Windows XP Icon 13.ico</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Icon=shell32.dll,331</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Settings=SPLIT</Line>
	</MenuItems>
	<Skin2 value="&lt;Kein Skin&gt;"/>
	<SkinVariation2 value=""/>
	<SkinOptions2 value=""/>
	<EnableStartButton value="1"/>
	<StartButtonTip value=""/>
	<StartButtonType value="ClasicButton"/>
	<StartButtonPath value=""/>
	<StartButtonSize value="0"/>
	<StartButtonIcon value="%SystemDrive%\Program Files\Classic Shell\Windows.ico"/>
</Settings>
