<?xml version="1.0"?>
<Settings component="StartMenu" version="4.0.2">
	<MenuStyle value="Classic2"/>
	<Favorites value="Menu"/>
	<Documents value="Hide"/>
	<RecentPrograms value="Recent"/>
	<RecentMetroApps value="0"/>
	<StartScreenShortcut value="0"/>
	<SearchBox value="Hide"/>
	<SmallIconSize value="16"/>
	<NoTaskbarTransparency2 value="0"/>
	<GlassOverride value="1"/>
	<GlassIntensity value="90"/>
	<GlassBlending value="0"/>
	<SkinC1 value="Windows 8"/>
	<SkinVariationC1 value=""/>
	<SkinOptionsC1 value="BD80CDB2|C26EAF5C|86F3669C|5225DC46|5D3248DD|1FC64124|5EA361A2|6EDFA36A|2E838408|22C9A1E2|0663DC39|"/>
	<SkinC2 value="Smoked Glass"/>
	<SkinVariationC2 value=""/>
	<SkinOptionsC2 value="E55CEDD2|C26EAF5C|86F3669C|5225DC46|5D3248DC|1FC64124|5EA361A2|"/>
	<SkinW7 value="Windows 8.1"/>
	<SkinVariationW7 value=""/>
	<SkinOptionsW7 value="C26EAF5C|5D3248DC|1FC64124|5EA361A2|6EDFA36A|2E838408|22C9A1E2|0663DC39|"/>
	<StartButtonType value="CustomButton"/>
	<StartButtonPath value="Z:\Classic start menu backup\Myselect Windows_#3_start Orb\Metro Button Size 1.bmp"/>
	<SkipMetro value="1"/>
	<DisableHotCorner value="DisableNone"/>
	<MenuItems1>
		<Line>Items=COLUMN_PADDING,ProgramsMenu,CustomItem3,CustomItem,CustomItem4,CustomItem5,CustomItem2,CustomItem6,CustomItem7,CustomItem8,CustomItem9,CustomItem10,CustomItem11,COLUMN_BREAK,SEPARATOR,ComputerItem,FavoritesItem,UserPicturesItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=All Programs</Line>
		<Line>ProgramsMenu.Tip=$Menu.ProgramsTip</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>CustomItem3.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Games</Line>
		<Line>CustomItem.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Audio Apps</Line>
		<Line>CustomItem4.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Photo Apps</Line>
		<Line>CustomItem5.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Video Apps</Line>
		<Line>CustomItem2.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Burner</Line>
		<Line>CustomItem6.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Utility Apps</Line>
		<Line>CustomItem7.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Browser</Line>
		<Line>CustomItem8.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Downloader</Line>
		<Line>CustomItem9.Link=%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Microsoft Office</Line>
		<Line>CustomItem10.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Security</Line>
		<Line>CustomItem11.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Maintenance</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=$Menu.Favorites</Line>
		<Line>FavoritesItem.Icon=shell32.dll,322</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
	</MenuItems1>
	<MenuItems2>
		<Line>Items=SEPARATOR,CustomItem10,CustomItem4,CustomItem5,CustomItem9,CustomItem7,CustomItem6,CustomItem2,CustomItem,CustomItem3,CustomItem8,ProgramsMenu,SearchBoxItem,COLUMN_BREAK,UserDocumentsItem,CustomItem11,UserPicturesItem,CustomItem12,CustomItem13,FavoritesItem,COLUMN_PADDING,SEPARATOR,ComputerItem,ControlPanelItem,SecurityItem,SEPARATOR,RestartItem,ShutdownItem</Line>
		<Line>CustomItem10.Link=%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Microsoft Office</Line>
		<Line>CustomItem10.Label=&amp;</Line>
		<Line>CustomItem10.Icon=%SystemDrive%\icons menu\MS Office.ico</Line>
		<Line>CustomItem4.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Audio</Line>
		<Line>CustomItem4.Label=&amp;</Line>
		<Line>CustomItem4.Icon=%SystemDrive%\icons menu\Audacity.ico</Line>
		<Line>CustomItem5.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Photo</Line>
		<Line>CustomItem5.Label=&amp;</Line>
		<Line>CustomItem5.Icon=%SystemDrive%\icons menu\Pictures.ico</Line>
		<Line>CustomItem9.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Video</Line>
		<Line>CustomItem9.Label=&amp;</Line>
		<Line>CustomItem9.Icon=%SystemDrive%\icons menu\My Video Apps.ico</Line>
		<Line>CustomItem7.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Downloader</Line>
		<Line>CustomItem7.Label=&amp;</Line>
		<Line>CustomItem7.Icon=%SystemDrive%\icons menu\Internet Download Manager.ico</Line>
		<Line>CustomItem6.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Browser</Line>
		<Line>CustomItem6.Label=&amp;</Line>
		<Line>CustomItem6.Icon=%SystemDrive%\icons menu\Internet Expljk.ico</Line>
		<Line>CustomItem2.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Burner</Line>
		<Line>CustomItem2.Label=&amp;</Line>
		<Line>CustomItem2.Icon=%SystemDrive%\icons menu\red.ico</Line>
		<Line>CustomItem.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Utility</Line>
		<Line>CustomItem.Label=&amp;</Line>
		<Line>CustomItem.Icon=%SystemDrive%\icons menu\Confgu.ico</Line>
		<Line>CustomItem3.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Games</Line>
		<Line>CustomItem3.Label=&amp;</Line>
		<Line>CustomItem3.Icon=%SystemDrive%\icons menu\Games alt.ico</Line>
		<Line>CustomItem8.Link=%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Security</Line>
		<Line>CustomItem8.Label=&amp;</Line>
		<Line>CustomItem8.Icon=%SystemDrive%\icons menu\Microsoft Security Essentials - Copy.ico</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=&amp;</Line>
		<Line>ProgramsMenu.Icon=%SystemDrive%\icons menu\My Apps.ico</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP|TRACK_RECENT</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Label=&amp;</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>UserDocumentsItem.Icon=%SystemDrive%\blue menu icons\Dockljkl;.ico</Line>
		<Line>CustomItem11.Link=::{031E4825-7B94-4DC3-B131-E946B44C8DD5}\Mus.library-ms</Line>
		<Line>CustomItem11.Label=&amp;</Line>
		<Line>CustomItem11.Icon=%SystemDrive%\blue menu icons\Muiui.ico</Line>
		<Line>CustomItem11.Settings=NOEXPAND</Line>
		<Line>UserPicturesItem.Link=::{031E4825-7B94-4DC3-B131-E946B44C8DD5}\Pictures.library-ms</Line>
		<Line>UserPicturesItem.Label=&amp;</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>UserPicturesItem.Icon=%SystemDrive%\blue menu icons\Doc.ico</Line>
		<Line>UserPicturesItem.Settings=NOEXPAND</Line>
		<Line>CustomItem12.Link=::{031E4825-7B94-4DC3-B131-E946B44C8DD5}\Videos.library-ms</Line>
		<Line>CustomItem12.Label=&amp;</Line>
		<Line>CustomItem12.Icon=%SystemDrive%\blue menu icons\Vide.ico</Line>
		<Line>CustomItem12.Settings=NOEXPAND</Line>
		<Line>CustomItem13.Link=Downloads | %USERPROFILE%\Downloads</Line>
		<Line>CustomItem13.Label=&amp;</Line>
		<Line>CustomItem13.Icon=%SystemDrive%\blue menu icons\Download Folderio.ico</Line>
		<Line>CustomItem13.Settings=NOEXPAND</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=&amp;</Line>
		<Line>FavoritesItem.Icon=%SystemDrive%\blue menu icons\guj.ico</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>ComputerItem.Label=&amp;</Line>
		<Line>ComputerItem.Icon=%SystemDrive%\blue menu icons\Systemui.ico</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=&amp;</Line>
		<Line>ControlPanelItem.Tip=$Menu.ControlPanelTip</Line>
		<Line>ControlPanelItem.Icon=%SystemDrive%\blue menu icons\Configurei.ico</Line>
		<Line>ControlPanelItem.Settings=TRACK_RECENT</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Tip=$Menu.SecurityTip</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=&amp;</Line>
		<Line>RestartItem.Tip=$Menu.RestartTip</Line>
		<Line>RestartItem.Icon=%SystemDrive%\icons menu\Power - Restart.ico</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=&amp;</Line>
		<Line>ShutdownItem.Tip=$Menu.ShutdownTip</Line>
		<Line>ShutdownItem.Icon=%SystemDrive%\icons menu\Power - Shut Down.ico</Line>
	</MenuItems2>
	<MenuItems7>
		<Line>Item1.Command=user_files</Line>
		<Line>Item1.Settings=NOEXPAND</Line>
		<Line>Item2.Command=lib_documents</Line>
		<Line>Item2.Settings=NOEXPAND</Line>
		<Line>Item3.Command=lib_pictures</Line>
		<Line>Item3.Settings=NOEXPAND</Line>
		<Line>Item4.Command=lib_music</Line>
		<Line>Item4.Settings=NOEXPAND</Line>
		<Line>Item5.Command=lib_videos</Line>
		<Line>Item5.Settings=ITEM_DISABLED</Line>
		<Line>Item6.Command=lib_tv</Line>
		<Line>Item6.Settings=ITEM_DISABLED</Line>
		<Line>Item7.Command=downloads</Line>
		<Line>Item7.Settings=ITEM_DISABLED</Line>
		<Line>Item8.Command=homegroup</Line>
		<Line>Item8.Settings=ITEM_DISABLED</Line>
		<Line>Item9.Command=separator</Line>
		<Line>Item10.Command=games</Line>
		<Line>Item10.Settings=TRACK_RECENT|NOEXPAND</Line>
		<Line>Item11.Command=favorites</Line>
		<Line>Item11.Settings=ITEM_DISABLED</Line>
		<Line>Item12.Command=recent_documents</Line>
		<Line>Item13.Command=network</Line>
		<Line>Item13.Settings=ITEM_DISABLED</Line>
		<Line>Item14.Command=network_connections</Line>
		<Line>Item14.Settings=ITEM_DISABLED</Line>
		<Line>Item15.Command=separator</Line>
		<Line>Item16.Command=control_panel</Line>
		<Line>Item16.Settings=TRACK_RECENT</Line>
		<Line>Item17.Command=admin</Line>
		<Line>Item17.Settings=TRACK_RECENT|ITEM_DISABLED</Line>
		<Line>Item18.Command=devices</Line>
		<Line>Item18.Settings=NOEXPAND</Line>
		<Line>Item19.Command=defaults</Line>
		<Line>Item20.Command=help</Line>
		<Line>Item21.Command=run</Line>
		<Line>Item22.Command=apps</Line>
		<Line>Item22.Settings=ITEM_DISABLED</Line>
		<Line>Item23.Command=windows_security</Line>
		<Line>Item24.Command=Shutdown.exe /s /t 0</Line>
		<Line>Item24.Label=Full Shutdown</Line>
		<Line>Item24.Settings=NOEXPAND</Line>
	</MenuItems7>
</Settings>
