<?xml version="1.0"?>
<Settings component="StartMenu" version="4.2.2">
	<MenuStyle value="Classic1"/>
	<MiddleClick value="WindowsMenu"/>
	<ShiftRight value="1"/>
	<Computer value="Hide"/>
	<MaxRecentDocuments value="25"/>
	<SortRecentDocuments value="Date"/>
	<ControlPanel value="Menu"/>
	<Network value="Menu"/>
	<Printers value="Menu"/>
	<ConfirmLogOff value="1"/>
	<Search value="0"/>
	<Help value="0"/>
	<RecentPrograms value="None"/>
	<RemoteShutdown value="1"/>
	<StartScreenShortcut value="0"/>
	<HighlightNew value="0"/>
	<SplitMenuDelay value="50"/>
	<ScrollType value="Scroll"/>
	<SearchBox value="Normal"/>
	<SearchInternet value="0"/>
	<SubMenuAnimationAlways value="1"/>
	<SkinC1 value="Full Glass"/>
	<SkinVariationC1 value=""/>
	<SkinOptionsC1 value="00000000|BD38A82D|0B805F82|678B22C0|BD80CDB3|C26EAF5C|86F3669C|5225DC46|5D3248DC|1FC64124|5EA361A3|"/>
	<SkinW7 value="Metro"/>
	<SkinVariationW7 value=""/>
	<SkinOptionsW7 value="C26EAF5D|5D3248DC|1FC64124|33C166BF|"/>
	<SkipMetro value="1"/>
	<MenuItems1>
		<Line>Items=COLUMN_PADDING,ProgramsMenu,AppsMenu,CustomItem16,RecentDocumentsItem,COLUMN_BREAK,ComputerItem,SettingsMenu,SearchMenu,RunItem,SEPARATOR,LogOffItem,UndockItem,DisconnectItem,ShutdownBoxItem,SEPARATOR,SearchBoxItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Tip=$Menu.ProgramsTip</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>AppsMenu.Command=apps</Line>
		<Line>AppsMenu.Label=$Menu.Apps</Line>
		<Line>AppsMenu.Icon=,2</Line>
		<Line>CustomItem16.Command=%USERPROFILE%\Downloads</Line>
		<Line>CustomItem16.Link=%USERPROFILE%\Downloads</Line>
		<Line>CustomItem16.Label=Downloads</Line>
		<Line>RecentDocumentsItem.Items=UserFilesItem,UserDocumentsItem,UserPicturesItem</Line>
		<Line>RecentDocumentsItem.Command=recent_documents</Line>
		<Line>RecentDocumentsItem.Label=Recent documents</Line>
		<Line>RecentDocumentsItem.Icon=shell32.dll,327</Line>
		<Line>RecentDocumentsItem.Settings=ITEMS_FIRST</Line>
		<Line>UserFilesItem.Command=user_files</Line>
		<Line>UserFilesItem.Tip=$Menu.UserFilesTip</Line>
		<Line>UserDocumentsItem.Command=user_documents</Line>
		<Line>UserDocumentsItem.Tip=$Menu.UserDocumentsTip</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>SettingsMenu.Items=ControlPanelItem,CustomItem6,NetworkItem,PrintersItem,SEPARATOR,MenuSettingsItem,TaskbarSettingsItem,SEPARATOR,ProgramsFeaturesItem,SecurityItem</Line>
		<Line>SettingsMenu.Command="shell:AppsFolder\windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel"</Line>
		<Line>SettingsMenu.Link="C:\Windows\explorer.exe"</Line>
		<Line>SettingsMenu.Label=Settings</Line>
		<Line>SettingsMenu.Icon=shell32.dll,330</Line>
		<Line>SettingsMenu.Settings=SPLIT</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Tip=$Menu.ControlPanelTip</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>ControlPanelItem.Settings=TRACK_RECENT|SPLIT</Line>
		<Line>CustomItem6.Items=CustomItem14,CustomItem8,CustomItem9,CustomItem12,CustomItem13,CustomItem7,CustomItem11,CustomItem10</Line>
		<Line>CustomItem6.Command=%SystemRoot%\System32\CompMgmtLauncher.exe</Line>
		<Line>CustomItem6.Label=Computer Management</Line>
		<Line>CustomItem6.Icon=%SystemRoot%\System32\CompMgmtLauncher.exe, 500</Line>
		<Line>CustomItem6.Settings=SPLIT</Line>
		<Line>CustomItem14.Command=%SystemRoot%\System32\devmgmt.msc</Line>
		<Line>CustomItem14.Label=Device Manager</Line>
		<Line>CustomItem14.Icon=C:\Windows\system32\devmgr.dll, 201</Line>
		<Line>CustomItem8.Command=%SystemRoot%\System32\diskmgmt.msc</Line>
		<Line>CustomItem8.Label=Disk Management</Line>
		<Line>CustomItem8.Icon=C:\Windows\system32\dmdskres.dll, 344</Line>
		<Line>CustomItem9.Command=%SystemRoot%\System32\eventvwr.msc</Line>
		<Line>CustomItem9.Label=Event Viewer</Line>
		<Line>CustomItem9.Icon=%SystemRoot%\system32\miguiresource.dll, 500</Line>
		<Line>CustomItem12.Command=%SystemRoot%\System32\lusrmgr.msc</Line>
		<Line>CustomItem12.Label=Local Users and Groups</Line>
		<Line>CustomItem12.Icon=C:\Windows\system32\localsec.dll, 5021</Line>
		<Line>CustomItem13.Command=%SystemRoot%\System32\perfmon.msc</Line>
		<Line>CustomItem13.Label=Performance Monitor</Line>
		<Line>CustomItem13.Icon=C:\Windows\system32\wdc.dll, 108</Line>
		<Line>CustomItem7.Command=%SystemRoot%\System32\services.msc</Line>
		<Line>CustomItem7.Label=Services</Line>
		<Line>CustomItem7.Icon=C:\Windows\system32\filemgmt.dll, 236</Line>
		<Line>CustomItem11.Command=%SystemRoot%\System32\fsmgmt.msc</Line>
		<Line>CustomItem11.Label=Shared Folders</Line>
		<Line>CustomItem11.Icon=C:\Windows\system32\filemgmt.dll, 237</Line>
		<Line>CustomItem10.Command=%SystemRoot%\System32\taskschd.msc</Line>
		<Line>CustomItem10.Label=Task Scheduler</Line>
		<Line>CustomItem10.Icon=%systemroot%\system32\miguiresource.dll, 600</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>NetworkItem.Settings=SPLIT</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>PrintersItem.Settings=SPLIT</Line>
		<Line>MenuSettingsItem.Command=menu_settings</Line>
		<Line>MenuSettingsItem.Label=Start Menu</Line>
		<Line>MenuSettingsItem.Tip=$Menu.SettingsTip</Line>
		<Line>MenuSettingsItem.Icon=,1</Line>
		<Line>TaskbarSettingsItem.Command=taskbar_settings</Line>
		<Line>TaskbarSettingsItem.Label=Taskbar</Line>
		<Line>TaskbarSettingsItem.Tip=$Menu.TaskbarTip</Line>
		<Line>TaskbarSettingsItem.Icon=shell32.dll,40</Line>
		<Line>ProgramsFeaturesItem.Command=programs_features</Line>
		<Line>ProgramsFeaturesItem.Label=$Menu.Features</Line>
		<Line>ProgramsFeaturesItem.Tip=$Menu.FeaturesTip</Line>
		<Line>ProgramsFeaturesItem.Icon=shell32.dll,271</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Tip=$Menu.SecurityTip</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>SearchMenu.Items=SearchFilesItem,SearchPrinterItem,SearchComputersItem,SearchPeopleItem</Line>
		<Line>SearchMenu.Command=search</Line>
		<Line>SearchMenu.Label=$Menu.Search</Line>
		<Line>SearchMenu.Icon=shell32.dll,323</Line>
		<Line>SearchFilesItem.Command=search_files</Line>
		<Line>SearchFilesItem.Label=$Menu.SearchFiles</Line>
		<Line>SearchFilesItem.Tip=$Menu.SearchFilesTip</Line>
		<Line>SearchFilesItem.Icon=shell32.dll,134</Line>
		<Line>SearchPrinterItem.Command=search_printer</Line>
		<Line>SearchPrinterItem.Label=$Menu.SearchPrinter</Line>
		<Line>SearchPrinterItem.Tip=$Menu.SearchPrintersTip</Line>
		<Line>SearchPrinterItem.Icon=shell32.dll,1006</Line>
		<Line>SearchComputersItem.Command=search_computers</Line>
		<Line>SearchComputersItem.Label=$Menu.SearchComputers</Line>
		<Line>SearchComputersItem.Tip=$Menu.SearchComputersTip</Line>
		<Line>SearchComputersItem.Icon=shell32.dll,135</Line>
		<Line>SearchPeopleItem.Command=search_people</Line>
		<Line>SearchPeopleItem.Label=$Menu.SearchPeople</Line>
		<Line>SearchPeopleItem.Icon=shell32.dll,269</Line>
		<Line>RunItem.Items=CustomItem5,CustomItem4,CustomItem2,CustomItem,CustomItem3,CustomItem15</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Tip=$Menu.RunTip</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>RunItem.Settings=SPLIT</Line>
		<Line>CustomItem5.Command=%SystemRoot%\System32\calc.exe</Line>
		<Line>CustomItem5.Label=Calculator</Line>
		<Line>CustomItem5.Icon=%SystemRoot%\System32\calc.exe, 234</Line>
		<Line>CustomItem4.Command=%SystemRoot%\System32\cmd.exe</Line>
		<Line>CustomItem4.Label=Command Prompt</Line>
		<Line>CustomItem4.Icon=%SystemRoot%\System32\cmd.exe</Line>
		<Line>CustomItem2.Command=%SystemRoot%\notepad.exe</Line>
		<Line>CustomItem2.Label=Notepad</Line>
		<Line>CustomItem2.Icon=%SystemRoot%\notepad.exe, 2</Line>
		<Line>CustomItem.Command=%SystemRoot%\regedit.exe</Line>
		<Line>CustomItem.Label=Registry Editor</Line>
		<Line>CustomItem.Icon=%SystemRoot%\regedit.exe, 100</Line>
		<Line>CustomItem3.Command=%SystemRoot%\System32\msconfig.exe</Line>
		<Line>CustomItem3.Label=System Configuration Utility</Line>
		<Line>CustomItem3.Icon=%SystemRoot%\System32\msconfig.exe, 128</Line>
		<Line>CustomItem15.Command=C:\Program Files\Windows NT\Accessories\wordpad.exe</Line>
		<Line>CustomItem15.Label=Wordpad</Line>
		<Line>CustomItem15.Icon=C:\Program Files\Windows NT\Accessories\wordpad.exe, 128</Line>
		<Line>LogOffItem.Items=LockItem,SwitchUserItem</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.Logoff</Line>
		<Line>LogOffItem.Tip=$Menu.LogOffTip</Line>
		<Line>LogOffItem.Icon=shell32.dll,325</Line>
		<Line>LogOffItem.Settings=OPEN_UP|SPLIT</Line>
		<Line>LockItem.Command=lock</Line>
		<Line>LockItem.Label=$Menu.Lock</Line>
		<Line>LockItem.Tip=$Menu.LockTip</Line>
		<Line>LockItem.Icon=shell32.dll, 48</Line>
		<Line>SwitchUserItem.Command=switch_user</Line>
		<Line>SwitchUserItem.Label=$Menu.SwitchUser</Line>
		<Line>SwitchUserItem.Tip=$Menu.SwitchUserTip</Line>
		<Line>SwitchUserItem.Icon=shell32.dll, 220</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Tip=$Menu.UndockTip</Line>
		<Line>UndockItem.Icon=shell32.dll,331</Line>
		<Line>DisconnectItem.Command=disconnect</Line>
		<Line>DisconnectItem.Label=$Menu.Disconnect</Line>
		<Line>DisconnectItem.Tip=$Menu.DisconnectTip</Line>
		<Line>DisconnectItem.Icon=%SystemRoot%\System32\imageres.dll, 5102</Line>
		<Line>ShutdownBoxItem.Items=MonitorOffItem,SleepItem,HibernateItem,SEPARATOR,RestartItem,ShutdownItem</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Settings=OPEN_UP|SPLIT</Line>
		<Line>MonitorOffItem.Command=monitor_off</Line>
		<Line>MonitorOffItem.Label=Monitor off</Line>
		<Line>MonitorOffItem.Tip=Turns off all displays connected to the computer</Line>
		<Line>MonitorOffItem.Icon=%SystemRoot%\System32\wmp.dll, 29106</Line>
		<Line>SleepItem.Command=sleep</Line>
		<Line>SleepItem.Label=$Menu.Sleep</Line>
		<Line>SleepItem.Tip=$Menu.SleepTip</Line>
		<Line>SleepItem.Icon=%SystemRoot%\System32\imageres.dll, 101</Line>
		<Line>HibernateItem.Command=hibernate</Line>
		<Line>HibernateItem.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem.Tip=$Menu.HibernateTip</Line>
		<Line>HibernateItem.Icon=none</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Tip=$Menu.RestartTip</Line>
		<Line>RestartItem.Icon=shell32.dll, 16739</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Tip=$Menu.ShutdownTip</Line>
		<Line>ShutdownItem.Icon=shell32.dll, 221</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP|TRACK_RECENT</Line>
	</MenuItems1>
	<SkinA value="&lt;No Skin&gt;"/>
	<SkinVariationA value=""/>
	<SkinOptionsA value="1FC64124|0663DC38|"/>
</Settings>
