<?xml version="1.0"?>
<Settings component="StartMenu" version="4.2.4">
	<MenuStyle value="Classic2"/>
	<MouseClick value="ClassicMenu"/>
	<WinKey value="Both"/>
	<MiddleClick value="WindowsMenu"/>
	<Favorites value="Hide"/>
	<UserFiles value="Hide"/>
	<UserDocuments value="Show"/>
	<UserPictures value="Hide"/>
	<Printers value="Hide"/>
	<Shutdown value="Menu"/>
	<LogOff value="1"/>
	<Undock value="0"/>
	<Search value="1"/>
	<Help value="0"/>
	<ProgramsStyle value="Inline"/>
	<OpenPrograms value="0"/>
	<ProgramsMenuDelay value="999999"/>
	<HideProgramsMetro value="0"/>
	<MaxRecentPrograms value="4"/>
	<RecentProgsTop value="0"/>
	<StartScreenShortcut value="0"/>
	<ScrollType value="NoScroll"/>
	<SameSizeColumns value="0"/>
	<EnableAccessibility value="0"/>
	<ReportSkinErrors value="1"/>
	<SearchBox value="Tab"/>
	<SearchSelect value="1"/>
	<SearchResults value="1"/>
	<SmallIconSize value="0"/>
	<MainMenuAnimation value="Fade"/>
	<MainMenuAnimationSpeed value="250"/>
	<SubMenuAnimation value="Fade"/>
	<SubMenuAnimationSpeed value="250"/>
	<MenuUsername value="Jcee"/>
	<MenuShadow value="0"/>
	<NoTaskbarTransparency2 value="0"/>
	<AeroGlass value="0"/>
	<EnableGlass value="1"/>
	<GlassOverride value="1"/>
	<GlassColor value="9866256"/>
	<GlassIntensity value="100"/>
	<GlassBlending value="100"/>
	<GlassOpacity value="90"/>
	<SkinC1 value="Classic Skin"/>
	<SkinVariationC1 value="Light"/>
	<SkinOptionsC1 value="BD80CDB3|C26EAF5C|86F3669C|5225DC46|5D3248DC|E87963C2|80316ABF|"/>
	<SkinC2 value="Windows XP Luna"/>
	<SkinVariationC2 value=""/>
	<SkinOptionsC2 value="5D3248DC|1FC64124|E55CEDD2|C26EAF5D|86F3669D|5225DC46|"/>
	<SkinW7 value="Windows 8"/>
	<SkinVariationW7 value="Light"/>
	<SkinOptionsW7 value="C26EAF5D|5D3248DC|1FC64124|5EA361A2|6EDFA36A|2BFF727F|2E838408|22C9A1E2|0663DC39|"/>
	<EnableStartButton value="0"/>
	<StartButtonType value="AeroButton"/>
	<StartButtonPath value="%USERPROFILE%\Downloads\Images\hal1 - Copie - Copie - Copie.png"/>
	<StartButtonSize value="55"/>
	<StartButtonIcon value="%USERPROFILE%\Desktop\Icon_1.ico"/>
	<StartButtonIconSize value="35"/>
	<StartButtonText value=""/>
	<SkipMetro value="1"/>
	<DisableHotCorner value="DisableNone"/>
	<CustomTaskbar value="1"/>
	<TaskbarColor value="14707984"/>
	<OpenMouseMonitor value="0"/>
	<MenuItems2>
		<Line>Items=COLUMN_PADDING,RecentDocumentsItem,ProgramsMenu,AppsMenu,SearchBoxItem,COLUMN_BREAK,FavoritesItem,UserFilesItem,UserPicturesItem,ComputerItem,SEPARATOR,ControlPanelItem,SecurityItem,NetworkItem,PrintersItem,SEPARATOR,SearchMenu,HelpItem,RunItem,COLUMN_PADDING,ShutdownBoxItem</Line>
		<Line>RecentDocumentsItem.Command=recent_documents</Line>
		<Line>RecentDocumentsItem.Label=$Menu.Documents</Line>
		<Line>RecentDocumentsItem.Icon=shell32.dll,327</Line>
		<Line>RecentDocumentsItem.Settings=ITEMS_FIRST</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Tip=Test</Line>
		<Line>ProgramsMenu.Icon=shell32.dll,326</Line>
		<Line>AppsMenu.Command=apps</Line>
		<Line>AppsMenu.Label=$Menu.Apps</Line>
		<Line>AppsMenu.Icon=,2</Line>
		<Line>SearchBoxItem.Command=search_box</Line>
		<Line>SearchBoxItem.Label=$Menu.SearchBox</Line>
		<Line>SearchBoxItem.Icon=none</Line>
		<Line>SearchBoxItem.Settings=OPEN_UP|TRACK_RECENT</Line>
		<Line>FavoritesItem.Command=favorites</Line>
		<Line>FavoritesItem.Label=$Menu.Favorites</Line>
		<Line>FavoritesItem.Icon=shell32.dll,322</Line>
		<Line>UserFilesItem.Command=user_files</Line>
		<Line>UserFilesItem.Tip=$Menu.UserFilesTip</Line>
		<Line>UserPicturesItem.Command=user_pictures</Line>
		<Line>UserPicturesItem.Tip=$Menu.UserPicturesTip</Line>
		<Line>ComputerItem.Command=computer</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Tip=$Menu.ControlPanelTip</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>ControlPanelItem.Settings=TRACK_RECENT</Line>
		<Line>SecurityItem.Command=windows_security</Line>
		<Line>SecurityItem.Label=$Menu.Security</Line>
		<Line>SecurityItem.Tip=$Menu.SecurityTip</Line>
		<Line>SecurityItem.Icon=shell32.dll,48</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=$Menu.Network</Line>
		<Line>NetworkItem.Tip=$Menu.NetworkTip</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>PrintersItem.Command=printers</Line>
		<Line>PrintersItem.Label=$Menu.Printers</Line>
		<Line>PrintersItem.Tip=$Menu.PrintersTip</Line>
		<Line>PrintersItem.Icon=shell32.dll,138</Line>
		<Line>SearchMenu.Items=SearchFilesItem,SearchPrinterItem,SearchComputersItem,SearchPeopleItem</Line>
		<Line>SearchMenu.Command=search</Line>
		<Line>SearchMenu.Label=$Menu.Search</Line>
		<Line>SearchMenu.Icon=shell32.dll,323</Line>
		<Line>SearchFilesItem.Command=search_files</Line>
		<Line>SearchFilesItem.Label=$Menu.SearchFiles</Line>
		<Line>SearchFilesItem.Tip=$Menu.SearchFilesTip</Line>
		<Line>SearchFilesItem.Icon=shell32.dll,134</Line>
		<Line>SearchPrinterItem.Command=search_printer</Line>
		<Line>SearchPrinterItem.Label=$Menu.SearchPrinter</Line>
		<Line>SearchPrinterItem.Tip=$Menu.SearchPrintersTip</Line>
		<Line>SearchPrinterItem.Icon=shell32.dll,1006</Line>
		<Line>SearchComputersItem.Command=search_computers</Line>
		<Line>SearchComputersItem.Label=$Menu.SearchComputers</Line>
		<Line>SearchComputersItem.Tip=$Menu.SearchComputersTip</Line>
		<Line>SearchComputersItem.Icon=shell32.dll,135</Line>
		<Line>SearchPeopleItem.Command=search_people</Line>
		<Line>SearchPeopleItem.Label=$Menu.SearchPeople</Line>
		<Line>SearchPeopleItem.Icon=shell32.dll,269</Line>
		<Line>HelpItem.Command=help</Line>
		<Line>HelpItem.Label=$Menu.Help</Line>
		<Line>HelpItem.Tip=$Menu.HelpTip</Line>
		<Line>HelpItem.Icon=shell32.dll,324</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Tip=$Menu.RunTip</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>ShutdownBoxItem.Items=SwitchUserItem,LogOffItem,LockItem,SEPARATOR,SleepItem,HibernateItem,SEPARATOR,RestartItem,UndockItem,DisconnectItem,ShutdownItem</Line>
		<Line>ShutdownBoxItem.Command=shutdown_box</Line>
		<Line>ShutdownBoxItem.Label=$Menu.ShutdownBox</Line>
		<Line>ShutdownBoxItem.Icon=shell32.dll,329</Line>
		<Line>ShutdownBoxItem.Settings=SPLIT</Line>
		<Line>SwitchUserItem.Command=switch_user</Line>
		<Line>SwitchUserItem.Label=$Menu.SwitchUser</Line>
		<Line>SwitchUserItem.Tip=$Menu.SwitchUserTip</Line>
		<Line>SwitchUserItem.Icon=none</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=$Menu.LogoffShort</Line>
		<Line>LogOffItem.Tip=$Menu.LogOffTip</Line>
		<Line>LogOffItem.Icon=none</Line>
		<Line>LockItem.Command=lock</Line>
		<Line>LockItem.Label=$Menu.Lock</Line>
		<Line>LockItem.Tip=$Menu.LockTip</Line>
		<Line>LockItem.Icon=none</Line>
		<Line>SleepItem.Command=sleep</Line>
		<Line>SleepItem.Label=$Menu.Sleep</Line>
		<Line>SleepItem.Tip=$Menu.SleepTip</Line>
		<Line>SleepItem.Icon=none</Line>
		<Line>HibernateItem.Command=hibernate</Line>
		<Line>HibernateItem.Label=$Menu.Hibernate</Line>
		<Line>HibernateItem.Tip=$Menu.HibernateTip</Line>
		<Line>HibernateItem.Icon=none</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=$Menu.Restart</Line>
		<Line>RestartItem.Tip=$Menu.RestartTip</Line>
		<Line>RestartItem.Icon=none</Line>
		<Line>UndockItem.Command=undock</Line>
		<Line>UndockItem.Label=$Menu.Undock</Line>
		<Line>UndockItem.Tip=$Menu.UndockTip</Line>
		<Line>UndockItem.Icon=none</Line>
		<Line>DisconnectItem.Command=disconnect</Line>
		<Line>DisconnectItem.Label=$Menu.Disconnect</Line>
		<Line>DisconnectItem.Tip=$Menu.DisconnectTip</Line>
		<Line>DisconnectItem.Icon=none</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=$Menu.Shutdown</Line>
		<Line>ShutdownItem.Tip=$Menu.ShutdownTip</Line>
		<Line>ShutdownItem.Icon=none</Line>
	</MenuItems2>
	<MenuItems7>
		<Line>Item1.Command=user_files</Line>
		<Line>Item1.Settings=NOEXPAND</Line>
		<Line>Item2.Command=user_documents</Line>
		<Line>Item2.Settings=NOEXPAND</Line>
		<Line>Item3.Command=user_pictures</Line>
		<Line>Item3.Settings=NOEXPAND</Line>
		<Line>Item4.Command=user_music</Line>
		<Line>Item4.Settings=NOEXPAND</Line>
		<Line>Item5.Command=user_videos</Line>
		<Line>Item5.Settings=ITEM_DISABLED</Line>
		<Line>Item6.Command=downloads</Line>
		<Line>Item6.Settings=ITEM_DISABLED</Line>
		<Line>Item7.Command=homegroup</Line>
		<Line>Item7.Settings=ITEM_DISABLED</Line>
		<Line>Item8.Command=separator</Line>
		<Line>Item9.Command=games</Line>
		<Line>Item9.Settings=TRACK_RECENT|ITEM_DISABLED</Line>
		<Line>Item10.Command=favorites</Line>
		<Line>Item10.Settings=ITEM_DISABLED</Line>
		<Line>Item11.Command=recent_documents</Line>
		<Line>Item12.Command=computer</Line>
		<Line>Item12.Settings=NOEXPAND</Line>
		<Line>Item13.Command=network</Line>
		<Line>Item13.Settings=ITEM_DISABLED</Line>
		<Line>Item14.Command=network_connections</Line>
		<Line>Item14.Settings=ITEM_DISABLED</Line>
		<Line>Item15.Command=separator</Line>
		<Line>Item16.Command=control_panel</Line>
		<Line>Item16.Settings=TRACK_RECENT</Line>
		<Line>Item17.Command=pc_settings</Line>
		<Line>Item17.Settings=TRACK_RECENT</Line>
		<Line>Item18.Command=admin</Line>
		<Line>Item18.Settings=TRACK_RECENT|ITEM_DISABLED</Line>
		<Line>Item19.Command=devices</Line>
		<Line>Item19.Settings=NOEXPAND</Line>
		<Line>Item20.Command=defaults</Line>
		<Line>Item20.Settings=ITEM_DISABLED</Line>
		<Line>Item21.Command=help</Line>
		<Line>Item21.Settings=ITEM_DISABLED</Line>
		<Line>Item22.Command=run</Line>
		<Line>Item22.Settings=ITEM_DISABLED</Line>
		<Line>Item23.Command=apps</Line>
		<Line>Item23.Settings=ITEM_DISABLED</Line>
		<Line>Item24.Command=windows_security</Line>
	</MenuItems7>
	<EnableContextMenu value="1"/>
</Settings>
