<?xml version="1.0"?>
<Settings component="StartMenu" version="3.6.8">
	<DefaultMenuStyle value="Classic"/>
	<WinKey value="Nothing"/>
	<Hover value="ClassicMenu"/>
	<StartHoverDelay value="0"/>
	<Computer value="Hide"/>
	<Documents value="Hide"/>
	<UserFiles value="Hide"/>
	<UserDocuments value="Hide"/>
	<UserPictures value="Hide"/>
	<ControlPanel value="Show"/>
	<Network value="Show"/>
	<Printers value="Hide"/>
	<Search value="0"/>
	<Help value="0"/>
	<LogOff value="1"/>
	<Undock value="0"/>
	<RecentPrograms value="0"/>
	<MenuDelay value="0"/>
	<MainMenuAnimation value="None"/>
	<EnableJumplists value="0"/>
	<EnableAccessibility value="0"/>
	<PreCacheIcons value="0"/>
	<ScrollType value="Scroll"/>
	<LargeIconSize value="25"/>
	<NumericSort value="1"/>
	<FontSmoothing value="ClearType"/>
	<SearchBox value="Hide"/>
	<Skin1 value="Windows Basic"/>
	<SkinVariation1 value="Default"/>
	<SkinOptions1 value="DA60029A|E55CEDD2|BD80CDB2|C26EAF5C|86F3669C|5225DC46|5D3248DC|1FC64124|0663DC39|5EA361A2|"/>
	<CascadingMenu value="1"/>
	<EnableExplorer value="0"/>
	<SoundMain value=""/>
	<SoundPopup value=""/>
	<SoundCommand value=""/>
	<SoundDrop value=""/>
	<MenuItems>
		<Line>Items=COLUMN_BREAK,ProgramsMenu,SettingsMenu,RunItem,SEPARATOR,ShutdownItem</Line>
		<Line>ProgramsMenu.Command=programs</Line>
		<Line>ProgramsMenu.Label=$Menu.Programs</Line>
		<Line>ProgramsMenu.Icon=shell32.dll, 16752</Line>
		<Line>SettingsMenu.Items=ControlPanelItem,NetworkItem,SEPARATOR,SwitchUserItem,LogOffItem,RestartItem</Line>
		<Line>SettingsMenu.Command=settings</Line>
		<Line>SettingsMenu.Label=$Menu.Settings</Line>
		<Line>SettingsMenu.Icon=shell32.dll,330</Line>
		<Line>ControlPanelItem.Command=control_panel</Line>
		<Line>ControlPanelItem.Label=$Menu.ControlPanel</Line>
		<Line>ControlPanelItem.Icon=shell32.dll,137</Line>
		<Line>NetworkItem.Command=network_connections</Line>
		<Line>NetworkItem.Label=Networks</Line>
		<Line>NetworkItem.Icon=shell32.dll,257</Line>
		<Line>SwitchUserItem.Command=switch_user</Line>
		<Line>SwitchUserItem.Label=Switch</Line>
		<Line>SwitchUserItem.Icon=%SystemRoot%\System32\shell32.dll, 220</Line>
		<Line>LogOffItem.Command=logoff</Line>
		<Line>LogOffItem.Label=Logoff</Line>
		<Line>LogOffItem.Icon=shell32.dll,325</Line>
		<Line>RestartItem.Command=restart</Line>
		<Line>RestartItem.Label=Restart</Line>
		<Line>RestartItem.Icon=%systemroot%\system32\comres.dll, 2855</Line>
		<Line>RunItem.Command=run</Line>
		<Line>RunItem.Label=$Menu.Run</Line>
		<Line>RunItem.Icon=shell32.dll,328</Line>
		<Line>ShutdownItem.Command=shutdown</Line>
		<Line>ShutdownItem.Label=Shut Down</Line>
		<Line>ShutdownItem.Icon=shell32.dll,329</Line>
	</MenuItems>
	<Skin2 value="Windows Basic"/>
	<SkinVariation2 value=""/>
	<SkinOptions2 value="1FC64125|0663DC39|"/>
	<EnableStartButton value="0"/>
</Settings>
