#define IDS_VERSION                     16
#define IDS_NEWS                        17
#define IDS_INSTALL_URL                 18
#define IDS_INSTALL_SIGNER              19
#define IDS_LNG_URL                     20
#define IDS_LNG_VERSION                 21
#define IDS_LNG_CRC                     22
#define IDS_UPDATE_LINK                 23
#define IDS_LANGUAGE_LINK               24
#define IDS_ALT_URL                     25
