//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StartMenuDLL.rc
//
#define IDI_APPICON                     1
#define IDI_APPSICON                    2
#define IDD_RENAME                      102
#define IDC_EDITNAME                    102
#define IDD_RENAMER                     103
#define IDD_LOGOFF                      104
#define IDD_LOGOFFR                     105
#define IDB_SEARCH_ICONS                110
#define IDB_BUTTON96                    111
#define IDB_BUTTON120                   112
#define IDB_BUTTON144                   113
#define IDB_BUTTON180                   114
#define IDB_STYLE_CLASSIC1              120
#define IDB_STYLE_CLASSIC2              121
#define IDB_STYLE_WIN7                  122
#define IDB_BTN_CLASSIC                 124
#define IDI_BTN_CLASSIC                 125
#define IDI_START                       126
#define IDI_START10                     127
#define IDB_STYLE_CLASSIC1150           130
#define IDB_STYLE_CLASSIC2150           131
#define IDB_STYLE_WIN7150               132
#define IDC_STATICICON                  209
#define IDC_COMBOCOMMAND                239
#define IDC_EDITLABEL                   240
#define IDC_EDITTIP                     241
#define IDC_BUTTONLINK                  242
#define IDC_BUTTONCOMMAND               243
#define IDC_EDITICON                    245
#define IDC_BUTTONICON                  246
#define IDC_STATICCOMMAND               251
#define IDC_STATICLINK                  252
#define IDC_STATICTEXT                  253
#define IDC_STATICINFOTIP               254
#define IDC_ICONN                       256
#define IDC_COMBOLINK                   258
#define IDC_STATICHINT                  259
#define IDC_BUTTONRESET                 261
#define IDC_PROMPT                      1015
#define IDC_COMBOSKIN                   1019
#define IDB_ARROWS                      1020
#define IDC_ABOUT                       1020
#define IDB_ARROWS150                   1021
#define IDC_STATICOPT                   1023
#define IDC_STATICVER                   1025
#define IDC_LABEL                       1047
#define IDC_RADIO2                      1049
#define IDC_TREE2                       1052
#define IDC_SKINOPTIONS                 1052
#define IDC_STATICICON1                 1053
#define IDC_CHECKSORTZA                 1054
#define IDC_CHECKSORTZAREC              1055
#define IDC_CHECKSORTONCE               1056
#define IDC_CHECKOPENUP                 1057
#define IDC_CHECKOPENUPCHILDREN         1058
#define IDC_CHECKOPENUPREC              1058
#define IDC_CHECKNOEXPAND               1059
#define IDC_CHECKMULTICOLUMN            1060
#define IDC_BUTTON1                     1060
#define IDC_BUTTONPICK                  1060
#define IDC_CHECKTRACK                  1061
#define IDC_STATICSKIN                  1061
#define IDC_CHECKNOTRACK                1062
#define IDC_STATICALLPROGS              1062
#define IDC_CHECKITEMSFIRST             1063
#define IDC_CHECKINLINE                 1064
#define IDC_CHECK2                      1065
#define IDC_CHECKNOEXT                  1065
#define IDC_CHECKNOEXPAND2              1066
#define IDC_CHECKSPLIT                  1066
#define IDC_STATICTITLE                 1066
#define IDC_STATIC_CLASSIC              1067
#define IDC_STATIC_XP                   1068
#define IDC_STATIC_VISTA                1069
#define IDC_STATIC_WIN7                 1069
#define IDC_LINK_CLASSIC                1070
#define IDC_STATIC_WIN8                 1070
#define IDC_LINK_XP                     1071
#define IDC_RADIO_CLASSIC               1071
#define IDC_RADIO_TWO_COLUMNS           1072
#define IDC_RADIO_WIN7                  1073
#define IDC_LISTITEMS                   1073
#define IDC_EDITLINK2                   1075
#define IDC_STATIC_TWO_COLUMNS          1076
#define IDC_CHECKENABLED                1077
#define IDC_LINKADVANCED                1078
#define IDC_RADIOCLASSIC                1079
#define IDC_RADIOAERO                   1080
#define IDC_RADIOCUSTOM                 1081
#define IDC_STATICAERO                  1082
#define IDC_STATICCUSTOM                1083
#define IDC_STATICEDGE                  1084
#define IDC_STATICCLASSIC               1085
#define IDC_SKIN_CLASSIC                1086
#define IDC_SKIN_CLASSIC2               1087
#define IDC_SKIN_WIN7                   1088
#define IDC_STATICEDGE2                 1089
#define IDD_CUSTOMMENU                  3001
#define IDS_APP_TITLE                   3001
#define IDD_SKINSETTINGS                3002
#define IDS_SETTINGS_TITLE              3002
#define IDS_SETTINGS_TITLE_VER          3003
#define IDD_STYLESETTINGS               3003
#define IDS_NEW_SETTINGS                3004
#define IDD_CUSTOMMENU7                 3004
#define IDD_CUSTOMLIST                  3005
#define IDS_NO_TEXT                     3005
#define IDS_CTRL_CLASSIC                3006
#define IDS_CTRL_WINDOWS                3007
#define IDS_SETTINGS                    3008
#define IDS_SETTINGS_TIP                3009
#define IDS_SKIN_ERR_UNKNOWN            3010
#define IDS_SKIN_ERR_DISABLE            3011
#define IDS_SKIN_ERR                    3012
#define IDS_SKIN_WARN                   3013
#define IDS_SKIN_ABOUT                  3014
#define IDS_SKIN_FAIL                   3015
#define IDS_SKIN_ERR_BMPRES             3016
#define IDS_SKIN_ERR_BMPFILE            3017
#define IDS_SKIN_ERR_MASKRES            3018
#define IDS_SKIN_ERR_MASKFILE           3019
#define IDS_SKIN_ERR_MASKSIZE           3020
#define IDS_SKIN_ERR_FIND_RES1          3021
#define IDS_SKIN_ERR_LOAD_RES1          3022
#define IDS_SKIN_ERR_LOAD_FILE1         3023
#define IDS_SKIN_ERR_FIND_RES           3024
#define IDS_SKIN_ERR_LOAD_RES           3025
#define IDS_SKIN_ERR_LOAD_FILE          3026
#define IDS_SKIN_ERR_LOAD               3027
#define IDS_SKIN_ERR_VERSION            3028
#define IDS_MENU_TITLE                  3029
#define IDS_DEFAULT_SKIN                3030
#define IDS_CONTROLS_SETTINGS           3031
#define IDS_OPEN_NOTHING                3032
#define IDS_OPEN_NOTHING_TIP            3033
#define IDS_OPEN_CSM                    3034
#define IDS_OPEN_CSM_TIP                3035
#define IDS_OPEN_WSM                    3036
#define IDS_OPEN_WSM_TIP                3037
#define IDS_LCLICK                      3038
#define IDS_LCLICK_TIP                  3039
#define IDS_SHIFT_LCLICK                3040
#define IDS_SHIFT_LCLICK_TIP            3041
#define IDS_WIN_KEY                     3042
#define IDS_WIN_KEY_TIP                 3043
#define IDS_SHIFT_WIN                   3044
#define IDS_SHIFT_WIN_TIP               3045
#define IDS_MCLICK                      3046
#define IDS_MCLICK_TIP                  3047
#define IDS_HOVER                       3048
#define IDS_HOVER_TIP                   3049
#define IDS_HOVER_DELAY                 3050
#define IDS_HOVER_DELAY_TIP             3051
#define IDS_CSM_HOTKEY                  3052
#define IDS_CSM_HOTKEY_TIP              3053
#define IDS_WSM_HOTKEY                  3054
#define IDS_WSM_HOTKEY_TIP              3055
#define IDS_SHOW_ITEMS                  3056
#define IDS_ITEM_HIDE                   3057
#define IDS_ITEM_HIDE_TIP               3058
#define IDS_ITEM_SHOW                   3059
#define IDS_ITEM_SHOW_TIP               3060
#define IDS_ITEM_MENU                   3061
#define IDS_ITEM_MENU_TIP               3062
#define IDS_SHOW_FAVORITES              3063
#define IDS_SHOW_FAVORITES_TIP          3064
#define IDS_SHOW_DOCUMENTS              3065
#define IDS_SHOW_DOCUMENTS_TIP          3066
#define IDS_MAX_DOCS                    3067
#define IDS_MAX_DOCS_TIP                3068
#define IDS_SHOW_USERFILES              3069
#define IDS_SHOW_USERFILES_TIP          3070
#define IDS_SHOW_USERDOCS               3071
#define IDS_SHOW_USERDOCS_TIP           3072
#define IDS_SHOW_USERPICS               3073
#define IDS_SHOW_USERPICS_TIP           3074
#define IDS_SHOW_CP                     3075
#define IDS_SHOW_CP_TIP                 3076
#define IDS_SHOW_NETWORK                3077
#define IDS_SHOW_NETWORK_TIP            3078
#define IDS_SHOW_PRINTERS               3079
#define IDS_SHOW_PRINTERS_TIP           3080
#define IDS_SHOW_SEARCH                 3081
#define IDS_SHOW_SEARCH_TIP             3082
#define IDS_SHOW_HELP                   3083
#define IDS_SHOW_HELP_TIP               3084
#define IDS_SHOW_RUN                    3085
#define IDS_SHOW_RUN_TIP                3086
#define IDS_SHOW_LOGOFF                 3087
#define IDS_SHOW_LOGOFF_TIP             3088
#define IDS_CONFIRM_LOGOFF              3089
#define IDS_CONFIRM_LOGOFF_TIP          3090
#define IDS_SHOW_UNDOCK                 3091
#define IDS_SHOW_UNDOCK_TIP             3092
#define IDS_SHOW_SHUTDOWN               3093
#define IDS_SHOW_SHUTDOWN_TIP           3094
#define IDS_SHOW_RSHUTDOWN              3095
#define IDS_SHOW_RSHUTDOWN_TIP          3096
#define IDS_SHOW_RECENT_OLD             3097
#define IDS_SHOW_RECENT_TIP_OLD         3098
#define IDS_MAX_PROGS                   3099
#define IDS_MAX_PROGS_TIP               3100
#define IDS_RECENT_TOP                  3101
#define IDS_RECENT_TOP_TIP              3102
#define IDS_RECENT_KEYS                 3103
#define IDS_RECENT_KEYS_TIP             3104
#define IDS_KEY_NOTHING                 3105
#define IDS_KEY_NOTHING_TIP             3106
#define IDS_KEY_NORMAL                  3107
#define IDS_KEY_NORMAL_TIP              3108
#define IDS_KEY_DIGITS                  3109
#define IDS_KEY_DIGITS_TIP              3110
#define IDS_KEY_HIDDEN                  3111
#define IDS_KEY_HIDDEN_TIP              3112
#define IDS_BEHAVIOR_SETTINGS           3113
#define IDS_EXPAND_LINKS                3114
#define IDS_EXPAND_LINKS_TIP            3115
#define IDS_MENU_DELAY                  3116
#define IDS_MENU_DELAY_TIP              3117
#define IDS_TIP_DELAY                   3118
#define IDS_TIP_DELAY_TIP               3119
#define IDS_FTIP_DELAY                  3120
#define IDS_FTIP_DELAY_TIP              3121
#define IDS_ANIM_NONE                   3122
#define IDS_ANIM_NONE_TIP               3123
#define IDS_ANIM_FADE                   3124
#define IDS_ANIM_FADE_TIP               3125
#define IDS_ANIM_SLIDE                  3126
#define IDS_ANIM_SLIDE_TIP              3127
#define IDS_ANIMATION                   3128
#define IDS_ANIMATION_TIP               3129
#define IDS_ANIM_SPEED                  3130
#define IDS_ANIM_SPEED_TIP              3131
#define IDS_SUB_ANIMATION               3132
#define IDS_SUB_ANIMATION_TIP           3133
#define IDS_SUB_ANIM_SPEED              3134
#define IDS_SUB_ANIM_SPEED_TIP          3135
#define IDS_SCROLL_SPEED                3136
#define IDS_SCROLL_SPEED_TIP            3137
#define IDS_SUB_SCROLL_SPEED            3138
#define IDS_SUB_SCROLL_SPEED_TIP        3139
#define IDS_FADE_SPEED                  3140
#define IDS_FADE_SPEED_TIP              3141
#define IDS_DRAG_DELAY                  3142
#define IDS_DRAG_DELAY_TIP              3143
#define IDS_ACCESSIBILITY               3144
#define IDS_ACCESSIBILITY_TIP           3145
#define IDS_NEXTTASKBAR                 3146
#define IDS_NEXTTASKBAR_TIP             3147
#define IDS_SEARCH_COMMAND              3148
#define IDS_SEARCH_COMMAND_TIP          3149
#define IDS_CASCADE_MENU                3150
#define IDS_CASCADE_MENU_TIP            3151
#define IDS_CACHE_ICONS                 3152
#define IDS_CACHE_ICONS_TIP             3153
#define IDS_SKIN_ERRORS                 3154
#define IDS_SKIN_ERRORS_TIP             3155
#define IDS_LOOK_SETTINGS               3156
#define IDS_MENU_WIDTH                  3157
#define IDS_MENU_WIDTH_TIP              3158
#define IDS_SUBMENU_WIDTH               3159
#define IDS_SUBMENU_WIDTH_TIP           3160
#define IDS_SAME_COLUMNS                3161
#define IDS_SAME_COLUMNS_TIP            3162
#define IDS_MENU_CAPTION                3163
#define IDS_MENU_CAPTION_TIP            3164
#define IDS_MENU_USERNAME               3165
#define IDS_MENU_USERNAME_TIP           3166
#define IDS_PIC_COMMAND                 3167
#define IDS_PIC_COMMAND_TIP             3168
#define IDS_NAME_COMMAND                3169
#define IDS_NAME_COMMAND_TIP            3170
#define IDS_SMALL_SIZE_SM               3171
#define IDS_SMALL_SIZE_SM_TIP           3172
#define IDS_LARGE_SIZE_SM               3173
#define IDS_LARGE_SIZE_SM_TIP           3174
#define IDS_NUMERIC_SORT                3175
#define IDS_NUMERIC_SORT_TIP            3176
#define IDS_FONT_SMOOTHING              3177
#define IDS_FONT_SMOOTHING_TIP          3178
#define IDS_SMOOTH_DEFAULT              3179
#define IDS_SMOOTH_DEFAULT_TIP          3180
#define IDS_SMOOTH_NONE                 3181
#define IDS_SMOOTH_NONE_TIP             3182
#define IDS_SMOOTH_STD                  3183
#define IDS_SMOOTH_STD_TIP              3184
#define IDS_SMOOTH_CLEAR                3185
#define IDS_SMOOTH_CLEAR_TIP            3186
#define IDS_CONTEXT_MENU_SETTINGS       3187
#define IDS_DRAG_DROP                   3188
#define IDS_DRAG_DROP_TIP               3189
#define IDS_CONTEXT_MENU                3190
#define IDS_CONTEXT_MENU_TIP            3191
#define IDS_NEW_FOLDER                  3192
#define IDS_NEW_FOLDER_TIP              3193
#define IDS_EXIT                        3194
#define IDS_EXIT_TIP                    3195
#define IDS_SOUND_SETTINGS              3196
#define IDS_SOUND_MAIN                  3197
#define IDS_SOUND_MAIN_TIP              3198
#define IDS_SOUND_POPUP                 3199
#define IDS_SOUND_POPUP_TIP             3200
#define IDS_SOUND_COMMAND               3201
#define IDS_SOUND_COMMAND_TIP           3202
#define IDS_SOUND_DROP                  3203
#define IDS_SOUND_DROP_TIP              3204
#define IDS_WSM_SETTINGS                3205
#define IDS_CASCADE_ALL                 3206
#define IDS_CASCADE_ALL_TIP             3207
#define IDS_ALL_DELAY                   3208
#define IDS_ALL_DELAY_TIP               3209
#define IDS_ALL_SELECT                  3210
#define IDS_ALL_SELECT_TIP              3211
#define IDS_SELECT_SEARCH               3212
#define IDS_SELECT_SEARCH_TIP           3213
#define IDS_SELECT_BUTTON               3214
#define IDS_SELECT_BUTTON_TIP           3215
#define IDS_SKIN_SETTINGS               3216
#define IDS_ALL_SKIN_SETTINGS           3217
#define IDS_CUSTOM_SETTINGS             3218
#define IDS_LANGUAGE_SETTINGS_SM        3219
#define IDS_SCROLL_TYPE                 3220
#define IDS_SCROLL_TYPE_TIP             3221
#define IDS_SCROLL_NO                   3222
#define IDS_SCROLL_NO_TIP               3223
#define IDS_SCROLL_YES                  3224
#define IDS_SCROLL_YES_TIP              3225
#define IDS_SCROLL_AUTO                 3226
#define IDS_SCROLL_AUTO_TIP             3227
#define IDS_ANIM_RANDOM                 3228
#define IDS_ANIM_RANDOM_TIP             3229
#define IDC_SKINVARIATION               3230
#define IDS_COMMAND_TIP                 3231
#define IDS_LINK_TIP                    3232
#define IDS_TEXT_TIP                    3233
#define IDS_TIP_TIP                     3234
#define IDS_ICON_TIP                    3235
#define IDS_SORTZA_TIP                  3236
#define IDS_SORTZAREC_TIP               3237
#define IDS_SORTONCE_TIP                3238
#define IDS_OPENUP_TIP                  3239
#define IDS_OPENUPREC_TIP               3240
#define IDS_NOEXPAND_TIP                3241
#define IDS_MULTICOLUMN_TIP             3242
#define IDS_TRACK_TIP                   3243
#define IDS_NOTRACK_TIP                 3244
#define IDS_ITEMSFIRST_TIP              3245
#define IDS_MAIN_SORTZA                 3246
#define IDS_MAIN_SORTONCE               3247
#define IDS_SEPARATOR_TIP               3248
#define IDS_BREAK_TIP                   3249
#define IDS_PADDING_TIP                 3250
#define IDS_PROGRAMS_TIP                3251
#define IDS_FAVORITES_TIP               3252
#define IDS_DOCUMENTS_TIP               3253
#define IDS_USERFILES_TIP               3254
#define IDS_USERDOCS_TIP                3255
#define IDS_USERPICS_TIP                3256
#define IDS_CONTROLPANEL_TIP            3257
#define IDS_CONTROLPANEL2_TIP           3258
#define IDS_SECURITY_TIP                3259
#define IDS_NETWORK_TIP                 3260
#define IDS_PRINTERS_TIP                3261
#define IDS_RUN_TIP                     3262
#define IDS_HELP_TIP                    3263
#define IDS_LOGOFF_TIP                  3264
#define IDS_UNDOCK_TIP                  3265
#define IDS_DISCONNECT_TIP              3266
#define IDS_SHUTDOWNBOX_TIP             3267
#define IDS_SEARCHFI_TIP                3268
#define IDS_SEARCHPR_TIP                3269
#define IDS_SEARCHCO_TIP                3270
#define IDS_SEARCHPE_TIP                3271
#define IDS_TASKBAR_TIP                 3272
#define IDS_MENU_TIP                    3273
#define IDS_RECENT_TIP                  3274
#define IDS_SLEEP_TIP                   3275
#define IDS_HIBERNATE_TIP               3276
#define IDS_RESTART_TIP                 3277
#define IDS_SHUTDOWN_TIP                3278
#define IDS_SWITCH_TIP                  3279
#define IDS_CUSTOM_TIP                  3280
#define IDS_SEARCH_TIP                  3281
#define IDS_SETTINGS_MENU_TIP           3282
#define IDS_FEATURES_TIP                3283
#define IDS_RESTORE_TIP                 3284
#define IDS_SEARCH_BOX_TIP              3285
#define IDS_SEARCH_BOX                  3286
#define IDS_SHOW_SEARCH_BOX             3287
#define IDS_SHOW_SEARCH_BOX_TIP         3288
#define IDS_SEARCH_BOX_HIDE             3289
#define IDS_SEARCH_BOX_HIDE_TIP         3290
#define IDS_SEARCH_BOX_SHOW             3291
#define IDS_SEARCH_BOX_SHOW_TIP         3292
#define IDS_SEARCH_BOX_TAB              3293
#define IDS_SEARCH_BOX_TAB_TIP          3294
#define IDS_SEARCH_BOX_SEL              3295
#define IDS_SEARCH_BOX_SEL_TIP          3296
#define IDS_SEARCH_PATH                 3299
#define IDS_SEARCH_PATH_TIP             3300
#define IDS_SUB_WORD                    3301
#define IDS_SUB_WORD_TIP                3302
#define IDS_SEARCH_TRACK                3303
#define IDS_SEARCH_TRACK_TIP            3304
#define IDS_SEARCH_MAX                  3305
#define IDS_SEARCH_MAX_TIP              3306
#define IDS_SEARCH_AUTO                 3307
#define IDS_SEARCH_AUTO_TIP             3308
#define IDS_INLINE_TIP                  3309
#define IDS_NOEXTENSIONS_TIP            3310
#define IDS_DELAY_ICONS                 3311
#define IDS_DELAY_ICONS_TIP             3312
#define IDS_SHOW_FAVORITES_TIP2         3313
#define IDS_SHOW_DOCUMENTS_TIP2         3314
#define IDS_SHOW_USERFILES_TIP2         3315
#define IDS_SHOW_USERDOCS_TIP2          3316
#define IDS_SHOW_USERPICS_TIP2          3317
#define IDS_SHOW_CP_TIP2                3318
#define IDS_SHOW_NETWORK_TIP2           3319
#define IDS_SHOW_PRINTERS_TIP2          3320
#define IDS_SHOW_SHUTDOWN_TIP2          3321
#define IDS_SHOW_SEARCH_BOX_TIP2        3322
#define IDS_SHOW_SEARCH_TIP2            3323
#define IDS_SHOW_HELP_TIP2              3324
#define IDS_SHOW_RUN_TIP2               3325
#define IDS_SHOW_LOGOFF_TIP2            3326
#define IDS_SHOW_UNDOCK_TIP2            3327
#define IDS_LOCK_TIP                    3328
#define IDS_SUB_ANIM_ALWAYS             3329
#define IDS_SUB_ANIM_ALWAYS_TIP         3330
#define IDS_EXPLORER                    3331
#define IDS_EXPLORER_TIP                3332
#define IDS_EXPLORER_PATH               3333
#define IDS_EXPLORER_PATH_TIP           3334
#define IDS_HIDE_PIC                    3335
#define IDS_HIDE_PIC_TIP                3336
#define IDS_SORT_DOCS                   3337
#define IDS_SORT_DOCS_TIP               3338
#define IDS_SORT_NAME                   3339
#define IDS_SORT_NAME_TIP               3340
#define IDS_SORT_EXT                    3341
#define IDS_SORT_EXT_TIP                3342
#define IDS_MENU_SHADOW                 3343
#define IDS_MENU_SHADOW_TIP             3344
#define IDS_START_BUTTON                3345
#define IDS_ENABLE_BUTTON               3346
#define IDS_ENABLE_BUTTON_TIP           3347
#define IDS_BUTTON_TYPE                 3348
#define IDS_BUTTON_TYPE_TIP             3349
#define IDS_CLASSIC_BUTTON              3350
#define IDS_CLASSIC_BUTTON_TIP          3351
#define IDS_AERO_BUTTON                 3352
#define IDS_AERO_BUTTON_TIP             3353
#define IDS_CUSTOM_BUTTON               3356
#define IDS_CUSTOM_BUTTON_TIP           3357
#define IDS_BUTTON_IMAGE                3358
#define IDS_BUTTON_IMAGE_TIP            3359
#define IDS_BUTTON_SIZE                 3360
#define IDS_BUTTON_SIZE_TIP             3361
#define IDS_HOT_CORNERS                 3362
#define IDS_HOT_CORNERS_TIP             3363
#define IDS_SKIP_METRO                  3364
#define IDS_SKIP_METRO_TIP              3365
#define IDS_BUTTON_ICON                 3366
#define IDS_BUTTON_ICON_TIP             3367
#define IDS_BUTTON_TIP                  3368
#define IDS_BUTTON_TIP_TIP              3369
#define IDS_BUTTON_TEXT                 3370
#define IDS_BUTTON_TEXT_TIP             3371
#define IDS_METRO_SETTINGS              3372
#define IDS_DISABLE_NONE                3373
#define IDS_DISABLE_NONE_TIP            3374
#define IDS_DISABLE_START               3375
#define IDS_DISABLE_START_TIP           3376
#define IDS_DISABLE_ALL                 3377
#define IDS_DISABLE_ALL_TIP             3378
#define IDS_ENABLE_BUTTON2              3379
#define IDS_ENABLE_BUTTON_TIP2          3380
#define IDS_SPLIT_TIP                   3381
#define IDS_STYLE_SETTINGS              3382
#define IDS_OPEN_WSS                    3384
#define IDS_OPEN_WSS_TIP                3385
#define IDS_WSS_HOTKEY                  3386
#define IDS_WSS_HOTKEY_TIP              3387
#define IDS_JUMPLISTS                   3388
#define IDS_JUMPLISTS_TIP               3389
#define IDS_MAX_JUMPLISTS               3390
#define IDS_MAX_JUMPLISTS_TIP           3391
#define IDS_JUMPLIST_KEYS               3392
#define IDS_JUMPLISTS_KEY_TIP           3393
#define IDS_KEY_SELECT                  3394
#define IDS_KEY_SELECT_TIP              3395
#define IDS_KEY_RUN                     3396
#define IDS_KEY_RUN_TIP                 3397
#define IDS_KEY_OPEN                    3398
#define IDS_KEY_OPEN_TIP                3399
#define IDS_APPS_TIP                    3400
#define IDS_SPLIT_DELAY                 3401
#define IDS_SPLIT_DELAY_TIP             3402
#define IDS_OPEN_BOTH                   3403
#define IDS_OPEN_BOTH_TIP               3404
#define IDS_SHOW_COMPUTER               3405
#define IDS_COMPUTER_TIP                3406
#define IDS_SHOW_COMPUTER_TIP           3407
#define IDS_SHOW_COMPUTER_TIP2          3408
#define IDS_OPEN_DESKTOP                3409
#define IDS_OPEN_DESKTOP_TIP            3410
#define IDS_SORT_DATE                   3411
#define IDS_SORT_DATE_TIP               3412
#define IDS_ENABLE_TASKBARS             3413
#define IDS_ENABLE_TASKBARS_TIP         3414
#define IDS_TASKBAR_TRANS               3415
#define IDS_TASKBAR_TRANS_TIP           3416
#define IDS_SEARCH_PROGRAMS             3417
#define IDS_SEARCH_PROGRAMS_TIP         3418
#define IDS_SEARCH_METRO                3419
#define IDS_SEARCH_METRO_TIP            3420
#define IDS_SEARCH_KEYWORDS             3423
#define IDS_SEARCH_KEYWORDS_TIP         3424
#define IDS_SEARCH_FILES                3425
#define IDS_SEARCH_FILES_TIP            3426
#define IDS_SEARCH_FILES_TIP2           3427
#define IDS_SEARCH_CONTENTS             3428
#define IDS_SEARCH_CONTENTS_TIP         3429
#define IDS_SEARCH_CATEGORIES           3430
#define IDS_SEARCH_CATEGORIES_TIP       3431
#define IDS_SEARCH_EVERYWHERE           3432
#define IDS_SEARCH_EVERYWHERE_TIP       3433
#define IDS_SEARCH_INTERNET             3434
#define IDS_SEARCH_INTERNET_TIP         3435
#define IDS_NO_RECENT                   3436
#define IDS_NO_RECENT_TIP               3437
#define IDS_RECENT_PROGRAMS             3438
#define IDS_RECENT_PROGRAMS_TIP         3439
#define IDS_SHOW_RECENT                 3440
#define IDS_SHOW_RECENT_TIP             3441
#define IDS_SHOW_FREQUENT               3442
#define IDS_SHOW_FREQUENT_TIP           3443
#define IDS_RECENT_METRO                3444
#define IDS_RECENT_METRO_TIP            3445
#define IDS_HIGHLIGHT_NEW               3446
#define IDS_HIGHLIGHT_NEW_TIP           3447
#define IDS_CP_CATEGORIES               3448
#define IDS_CP_CATEGORIES2              3449
#define IDS_CP_CATEGORIES_TIP           3450
#define IDS_CLASSIC_STYLE_TIP           3451
#define IDS_TWO_COLUMN_STYLE_TIP        3452
#define IDS_WIN7_STYLE_TIP              3453
#define IDS_SHUTDOWN_COMMAND            3454
#define IDS_SHUTDOWN_COMMAND_TIP        3455
#define IDS_SHUTDOWN_NONE               3456
#define IDS_SHUTDOWN_NONE_TIP           3457
#define IDS_SHUTDOWN_SHUTDOWN           3458
#define IDS_SHUTDOWN_SHUTDOWN_TIP       3459
#define IDS_SHUTDOWN_RESTART            3460
#define IDS_SHUTDOWN_RESTART_TIP        3461
#define IDS_SHUTDOWN_LOGOFF             3462
#define IDS_SHUTDOWN_LOGOFF_TIP         3463
#define IDS_SHUTDOWN_SLEEP              3464
#define IDS_SHUTDOWN_SLEEP_TIP          3465
#define IDS_SHUTDOWN_HIBERNATE          3466
#define IDS_SHUTDOWN_HIBERNATE_TIP      3467
#define IDS_SHUTDOWN_LOCK               3468
#define IDS_SHUTDOWN_LOCK_TIP           3469
#define IDS_SHUTDOWN_SWITCH             3470
#define IDS_SHUTDOWN_SWITCH_TIP         3471
#define IDS_SHUTDOWN_SHUTDOWN_BOX       3472
#define IDS_SHUTDOWN_SHUTDOWN_BOX_TIP   3473
#define IDS_UNDOCK_ITEM                 3474
#define IDS_DISCONNECT_ITEM             3475
#define IDS_ITEM_SHOW2                  3476
#define IDS_SEPARATOR_ITEM              3477
#define IDS_COLUMN_BREAK_ITEM           3478
#define IDS_COLUMN_PADDING_ITEM         3479
#define IDS_CUSTOM_ITEM                 3480
#define IDS_HELP_ITEM                   3481
#define IDS_RUN_ITEM                    3482
#define IDS_SECURITY_ITEM               3483
#define IDS_LIB_DOCS_ITEM               3484
#define IDS_LIB_PICS_ITEM               3485
#define IDS_LIB_VIDEOS_ITEM             3486
#define IDS_LIB_MUSIC_ITEM              3487
#define IDS_LIB_TV_ITEM                 3488
#define IDS_PROGRAMS_ITEM               3489
#define IDS_APPS_ITEM                   3490
#define IDS_SETTINGS_ITEM               3491
#define IDS_SEARCH_MENU_ITEM            3492
#define IDS_SEARCH_BOX_ITEM             3493
#define IDS_TASKBAR_ITEM                3494
#define IDS_FEATURES_ITEM               3495
#define IDS_MENU_SETTINGS_ITEM          3496
#define IDS_SEARCH_FILES_ITEM           3497
#define IDS_SEARCH_PRINTER_ITEM         3498
#define IDS_SEARCH_COMP_ITEM            3499
#define IDS_SEARCH_PEOPLE_ITEM          3500
#define IDS_MONITOR_OFF_ITEM            3501
#define IDS_MENU_MOVE_UP                3502
#define IDS_MENU_MOVE_DOWN              3503
#define IDS_MENU_INSERT                 3504
#define IDS_MENU_DUPLICATE              3505
#define IDS_METRO_APPS                  3506
#define IDS_PROGRAMS_DELAY              3507
#define IDS_PROGRAMS_DELAY_TIP          3508
#define IDS_SEARCH_MAX2                 3509
#define IDS_SEARCH_MAX_TIP2             3510
#define IDS_SEARCH_MAX3                 3511
#define IDS_SEARCH_MAX_TIP3             3512
#define IDS_SHOW_APPS                   3513
#define IDS_SHOW_APPS_TIP               3514
#define IDS_FOLDERS_FIRST               3515
#define IDS_FOLDERS_FIRST_TIP           3516
#define IDS_PINNED_PROGRAMS             3517
#define IDS_PINNED_PROGRAMS_TIP         3518
#define IDS_FAST_ITEMS                  3519
#define IDS_FAST_ITEMS_TIP              3520
#define IDS_PINNED_ITEMS                3521
#define IDS_PINNED_ITEMS_TIP            3522
#define IDS_BUTTON_ICON_SIZE            3523
#define IDS_BUTTON_ICON_SIZE_TIP        3524
#define IDS_BUTTON_SIZE_TIP2            3525
#define IDS_MONITOR_OFF_TIP             3526
#define IDS_AUTOSTART                   3527
#define IDS_AUTOSTART_TIP               3528
#define IDS_CHECK_UPDATES               3529
#define IDS_CHECK_UPDATES_TIP           3530
#define IDS_ITEM_DRIVES                 3531
#define IDS_ITEM_DRIVES_TIP             3532
#define IDS_MENU_GLASS                  3533
#define IDS_MENU_GLASS_TIP              3534
#define IDS_MAIN_MENU_SETTINGS          3535
#define IDS_RIGHT_SHIFT                 3538
#define IDS_RIGHT_SHIFT_TIP             3539
#define IDS_RIGHT_SHIFTX                3540
#define IDS_RIGHT_SHIFTX_TIP            3541
#define IDS_STARTSCREEN_ITEM            3542
#define IDS_STARTSCREEN_ITEM_TIP        3543
#define IDS_MIN_HEIGHT                  3544
#define IDS_MIN_HEIGHT_TIP              3545
#define IDS_GLASS_OVERRIDE              3546
#define IDS_GLASS_OVERRIDE_TIP          3547
#define IDS_GLASS_COLOR                 3548
#define IDS_GLASS_COLOR_TIP             3549
#define IDS_GLASS_INTENSITY             3550
#define IDS_GLASS_INTENSITY_TIP         3551
#define IDS_GLASS_BLENDING              3552
#define IDS_GLASS_BLENDING_TIP          3553
#define IDS_INLINE_PROGS                3554
#define IDS_INLINE_PROGS_TIP            3555
#define IDS_MAIN_INLINE                 3556
#define IDS_MAIN_INLINE_TIP             3557
#define IDS_MAIN_CASCADE                3558
#define IDS_MAIN_CASCADE_TIP            3559
#define IDS_ANIMATION7                  3560
#define IDS_ANIMATION7_TIP              3561
#define IDS_METRO_SETTINGS81            3562
#define IDS_MENU_BUSY                   3563
#define IDS_OPEN_PROGRAMS               3564
#define IDS_OPEN_PROGRAMS_TIP           3565
#define IDS_MOUSE_MONITOR               3566
#define IDS_MOUSE_MONITOR_TIP           3567
#define IDS_COLUMN_ICON                 3568
#define IDS_COLUMN_COMMAND              3569
#define IDS_COLUMN_DISPLAY              3570
#define IDS_HIDE_APPS                   3571
#define IDS_HIDE_APPS_TIP               3572
#define IDS_HYBRID_SHUTDOWN             3573
#define IDS_HYBRID_SHUTDOWN_TIP         3574
#define IDS_UPGRADE_WIN                 3575
#define IDS_UPGRADE_ERROR               3576
#define IDS_UPGRADE_SUCCESS             3577
#define IDS_INVERT_ICONS                3578
#define IDS_INVERT_ICONS_TIP            3579
#define IDS_SHUTDOWN7                   3580
#define IDS_SHUTDOWN7_TIP               3581
#define IDS_PROG_WIDTH                  3582
#define IDS_PROG_WIDTH_TIP              3583
#define IDS_JUMP_WIDTH                  3584
#define IDS_JUMP_WIDTH_TIP              3585
#define IDS_NOPIN                       3586
#define IDS_NOPIN_TIP                   3587
#define IDS_RECENT_NAME                 3588
#define IDS_RECENT_NAME_TIP             3589
#define IDS_DPI_OVERRIDE                3590
#define IDS_DPI_OVERRIDE_TIP            3591
#define IDS_ENABLE_TOUCH                3592
#define IDS_ENABLE_TOUCH_TIP            3593
#define IDS_METRO_SETTINGS10            3594
#define IDS_MOUSE_MONITOR2              3595
#define IDS_MOUSE_MONITOR_TIP2          3596
#define IDS_PIC_PATH                    3597
#define IDS_PIC_PATH_TIP                3598
#define IDS_SEARCH_METROS               3599
#define IDS_SEARCH_METROS_TIP           3600
#define IDS_SHOW_APPS_MENU              3601
#define IDS_SHOW_APPS_MENU_TIP          3602
#define IDS_SHOW_APPS_MENU_TIP2         3603
#define IDS_SKIN_ERR_METRO_COLOR        3604
#define IDS_BUTTON_ALIGN                3605
#define IDS_BUTTON_ALIGN_TIP            3606
#define IDS_MENU_GLASS2                 3607
#define IDS_MENU_GLASS2_TIP             3608
#define IDS_GLASS_OPACITY               3609
#define IDS_GLASS_OPACITY_TIP           3610
#define IDS_TASK_CUSTOM                 3611
#define IDS_TASK_CUSTOM_TIP             3612
#define IDS_TASK_LOOK                   3613
#define IDS_TASK_LOOK_TIP               3614
#define IDS_TASK_OPAQUE                 3615
#define IDS_TASK_OPAQUE_TIP             3616
#define IDS_TASK_TRANS                  3617
#define IDS_TASK_TRANS_TIP              3618
#define IDS_TASK_GLASS                  3619
#define IDS_TASK_GLASS_TIP              3620
#define IDS_TASK_AEROGLASS              3621
#define IDS_TASK_AEROGLASS_TIP          3622
#define IDS_TASK_OPACITY                3623
#define IDS_TASK_OPACITY_TIP            3624
#define IDS_TASK_COLOR                  3625
#define IDS_TASK_COLOR_TIP              3626
#define IDS_PCSETTINGS                  3627
#define IDS_PCSETTINGS_TIP              3628
#define IDS_HIGHLIGHT_NEWAPPS           3629
#define IDS_HIGHLIGHT_NEWAPPS_TIP       3630
#define IDS_OPEN_CORTANA                3631
#define IDS_OPEN_CORTANA_TIP            3632
#define IDS_SKIN_ERR_RECBITMAP          3633
#define IDS_MAIN_HIDDEN                 3634
#define IDS_MAIN_HIDDEN_TIP             3635
#define IDS_SOUND_HOVER                 3636
#define IDS_SOUND_HOVER_TIP             3637
#define IDS_SHUTDOWN_SHUTDOWN_NU        3638
#define IDS_SHUTDOWN_NU_TIP             3639
#define IDS_SHUTDOWN_RESTART_NU         3640
#define IDS_RESTART_NU_TIP              3641
#define IDS_TASK_TEXTURE                3642
#define IDS_TASK_TEXTURE_TIP            3643
#define IDS_TASK_STRETCHH               3644
#define IDS_TASK_STRETCHH_TIP           3645
#define IDS_TASK_STRETCHV               3646
#define IDS_TASK_STRETCHV_TIP           3647
#define IDS_TASK_STRETCH                3648
#define IDS_TASK_STRETCH_TIP            3649
#define IDS_TASK_TILE                   3650
#define IDS_TASK_TILE_TIP               3651
#define IDS_TASK_BORDERS                3652
#define IDS_TASK_BORDERS_TIP            3653
#define IDS_TASKBAR_SETTINGS            3654
#define IDS_TASK_TEXTCOLOR              3655
#define IDS_TASK_TEXTCOLOR_TIP          3656
#define IDS_SELECT_LAST                 3657
#define IDS_SELECT_LAST_TIP             3658
#define IDS_CLEAR_CACHE                 3659
#define IDS_ALIGN_WORK_AREA             3660
#define IDS_ALIGN_WORK_AREA_TIP         3661
#define IDS_HOR_OFFSET                  3662
#define IDS_HOR_OFFSET_TIP              3663
#define IDS_VERT_OFFSET                 3664
#define IDS_VERT_OFFSET_TIP             3665
#define IDS_STRING7001                  7001
#define IDS_STRING7002                  7002
#define IDS_STRING7003                  7003
#define IDS_STRING7004                  7004
#define IDS_STRING7005                  7005
#define IDS_STRING7006                  7006
#define IDS_STRING7007                  7007
#define IDS_STRING7008                  7008
#define IDS_STRING7009                  7009
#define IDS_STRING7010                  7010
#define IDS_STRING7011                  7011
#define IDS_STRING7012                  7012
#define IDS_STRING7013                  7013
#define IDS_STRING7014                  7014
#define IDS_STRING7015                  7015
#define IDS_STRING7016                  7016
#define IDS_STRING7017                  7017
#define IDS_STRING7018                  7018
#define IDS_STRING7019                  7019
#define IDS_STRING7020                  7020
#define IDS_STRING7021                  7021
#define IDS_STRING7022                  7022
#define IDS_STRING7023                  7023
#define IDS_STRING7024                  7024
#define IDS_STRING7025                  7025
#define IDS_STRING7026                  7026
#define IDS_STRING7027                  7027
#define IDS_STRING7028                  7028
#define IDS_STRING7029                  7029
#define IDS_STRING7030                  7030
#define IDS_STRING7031                  7031
#define IDS_STRING7032                  7032
#define IDS_STRING7033                  7033
#define IDS_STRING7034                  7034
#define IDS_STRING7035                  7035
#define IDS_STRING7036                  7036
#define IDS_STRING7037                  7037
#define IDS_STRING7038                  7038
#define IDS_STRING7100                  7100
#define IDS_STRING7101                  7101
#define IDS_STRING7102                  7102
#define IDS_STRING7103                  7103
#define IDS_STRING7104                  7104
#define IDS_STRING7105                  7105
#define IDS_STRING7106                  7106
#define IDS_STRING7107                  7107
#define IDS_STRING7108                  7108
#define IDS_STRING7109                  7109
#define IDS_STRING7110                  7110

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
